window.FOOD_DATABASE = [
  { name: "全脂奶", category: "乳制品", portion: "130g", protein: 4, sodium: 32, potassium: 172, phosphorus: 113, energy: 79, tags: ["dairy", "moderateK"], sourcePage: 123 },
  { name: "脱脂酸奶", category: "乳制品", portion: "120g", protein: 4, sodium: 33, potassium: 187, phosphorus: 109, energy: 68, tags: ["dairy", "moderateK"], sourcePage: 123 },
  { name: "果粒酸奶", category: "乳制品", portion: "130g", protein: 4, sodium: 42, potassium: 144, phosphorus: 117, energy: 87, tags: ["dairy", "moderateK"], sourcePage: 123 },
  { name: "全脂奶粉", category: "乳制品", portion: "20g", protein: 4, sodium: 52, potassium: 89, phosphorus: 93, energy: 95, tags: ["dairy", "lowK"], sourcePage: 123 },
  { name: "低脂奶粉", category: "乳制品", portion: "15g", protein: 4, sodium: 60, potassium: 198, phosphorus: 141, energy: 63, tags: ["dairy", "highP"], sourcePage: 123 },
  { name: "酸奶", category: "乳制品", portion: "160g", protein: 4, sodium: 64, potassium: 240, phosphorus: 136, energy: 115, tags: ["dairy", "highK"], sourcePage: 123 },
  { name: "脱脂奶", category: "乳制品", portion: "140g", protein: 4, sodium: 164, potassium: 286, phosphorus: 134, energy: 46, tags: ["dairy", "highK"], sourcePage: 123 },
  { name: "低脂奶酪", category: "乳制品", portion: "20g", protein: 4, sodium: 337, potassium: 74, phosphorus: 121, energy: 48, tags: ["dairy", "highNa"], sourcePage: 123 },
  { name: "低脂奶", category: "乳制品", portion: "140g", protein: 4, sodium: 391, potassium: 259, phosphorus: 127, energy: 60, tags: ["dairy", "highNa"], sourcePage: 123 },
  { name: "奶酪", category: "乳制品", portion: "25g", protein: 4, sodium: 400, potassium: 79, phosphorus: 97, energy: 87, tags: ["dairy", "highNa", "highP"], sourcePage: 123 },
  { name: "鹌鹑蛋", category: "蛋类", portion: "55g", protein: 7, sodium: 59, potassium: 190, phosphorus: 98, energy: 88, tags: ["protein", "egg"], sourcePage: 124 },
  { name: "鸡蛋", category: "蛋类", portion: "60g", protein: 7, sodium: 54, potassium: 55, phosphorus: 78, energy: 117, tags: ["protein", "egg", "lowK"], sourcePage: 124 },
  { name: "鸡蛋清", category: "蛋类", portion: "80g", protein: 7, sodium: 62, potassium: 13, phosphorus: 9, energy: 38, tags: ["protein", "egg", "lowK", "lowP"], sourcePage: 124 },
  { name: "鸡蛋黄", category: "蛋类", portion: "45g", protein: 7, sodium: 11, potassium: 0, phosphorus: 23, energy: 146, tags: ["protein", "egg"], sourcePage: 124 },
  { name: "松花鸭蛋", category: "蛋类", portion: "50g", protein: 7, sodium: 271, potassium: 231, phosphorus: 83, energy: 86, tags: ["protein", "egg", "highNa"], sourcePage: 124 },
  { name: "咸鸭蛋", category: "蛋类", portion: "55g", protein: 7, sodium: 1488, potassium: 338, phosphorus: 127, energy: 435, tags: ["protein", "egg", "veryHighNa"], sourcePage: 124 },
  { name: "鸭蛋清", category: "蛋类", portion: "70g", protein: 7, sodium: 50, potassium: 71, phosphorus: 11, energy: 33, tags: ["protein", "egg", "lowP"], sourcePage: 124 },
  { name: "鲅鱼", category: "水产", portion: "30g", protein: 6, sodium: 22, potassium: 111, phosphorus: 39, energy: 37, tags: ["protein", "fish", "lowP"], sourcePage: 124 },
  { name: "白姑鱼", category: "水产", portion: "35g", protein: 7, sodium: 53, potassium: 134, phosphorus: 60, energy: 53, tags: ["protein", "fish"], sourcePage: 124 },
  { name: "白米虾", category: "水产", portion: "40g", protein: 7, sodium: 36, potassium: 102, phosphorus: 106, energy: 32, tags: ["protein", "fish", "highP"], sourcePage: 124 },
  { name: "草鱼", category: "水产", portion: "40g", protein: 7, sodium: 184, potassium: 125, phosphorus: 81, energy: 73, tags: ["protein", "fish"], sourcePage: 125 },
  { name: "鲳鱼", category: "水产", portion: "35g", protein: 6, sodium: 22, potassium: 115, phosphorus: 54, energy: 49, tags: ["protein", "fish", "lowP"], sourcePage: 125 },
  { name: "大黄鱼", category: "水产", portion: "40g", protein: 7, sodium: 48, potassium: 104, phosphorus: 70, energy: 59, tags: ["protein", "fish"], sourcePage: 125 },
  { name: "鲜淡菜", category: "水产", portion: "60g", protein: 7, sodium: 270, potassium: 94, phosphorus: 118, energy: 50, tags: ["protein", "fish", "highNa"], sourcePage: 125 },
  { name: "鲷鱼", category: "水产", portion: "40g", protein: 7, sodium: 42, potassium: 104, phosphorus: 121, energy: 74, tags: ["protein", "fish", "highP"], sourcePage: 125 },
  { name: "海蜇皮", category: "水产", portion: "180g", protein: 7, sodium: 585, potassium: 288, phosphorus: 54, energy: 40, tags: ["protein", "fish", "veryHighNa"], sourcePage: 125 },
  { name: "鲜扇贝", category: "水产", portion: "60g", protein: 7, sodium: 184, potassium: 581, phosphorus: 302, energy: 48, tags: ["protein", "fish", "veryHighK", "veryHighP"], sourcePage: 126 },
  { name: "银鱼", category: "水产", portion: "40g", protein: 7, sodium: 3, potassium: 98, phosphorus: 9, energy: 48, tags: ["protein", "fish", "lowP"], sourcePage: 127 },
  { name: "泥鳅", category: "水产", portion: "65g", protein: 7, sodium: 33, potassium: 443, phosphorus: 190, energy: 57, tags: ["protein", "fish", "highK", "highP"], sourcePage: 127 },
  { name: "方腿", category: "家畜类", portion: "45g", protein: 6, sodium: 170, potassium: 96, phosphorus: 87, energy: 51, tags: ["protein", "meat"], sourcePage: 127 },
  { name: "牛肉后腿", category: "家畜类", portion: "40g", protein: 6, sodium: 25, potassium: 85, phosphorus: 63, energy: 36, tags: ["protein", "meat", "lean"], sourcePage: 127 },
  { name: "牛肉前腿", category: "家畜类", portion: "45g", protein: 7, sodium: 25, potassium: 97, phosphorus: 71, energy: 42, tags: ["protein", "meat", "lean"], sourcePage: 127 },
  { name: "牛腱子", category: "家畜类", portion: "15g", protein: 7, sodium: 62, potassium: 78, phosphorus: 71, energy: 84, tags: ["protein", "meat"], sourcePage: 127 },
  { name: "羊肉瘦", category: "家畜类", portion: "35g", protein: 7, sodium: 24, potassium: 138, phosphorus: 67, energy: 40, tags: ["protein", "meat", "lean"], sourcePage: 128 },
  { name: "猪瘦肉", category: "家畜类", portion: "35g", protein: 7, sodium: 20, potassium: 105, phosphorus: 65, energy: 49, tags: ["protein", "meat", "lean"], sourcePage: 128 },
  { name: "猪后臀", category: "家畜类", portion: "40g", protein: 7, sodium: 31, potassium: 77, phosphorus: 58, energy: 131, tags: ["protein", "meat"], sourcePage: 128 },
  { name: "鹌鹑", category: "家禽类", portion: "35g", protein: 7, sodium: 17, potassium: 71, phosphorus: 62, energy: 38, tags: ["protein", "poultry", "lowK"], sourcePage: 128 },
  { name: "鸡", category: "家禽类", portion: "40g", protein: 7, sodium: 24, potassium: 91, phosphorus: 56, energy: 96, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸽", category: "家禽类", portion: "40g", protein: 7, sodium: 25, potassium: 142, phosphorus: 58, energy: 85, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸡胸肉", category: "家禽类", portion: "35g", protein: 8, sodium: 14, potassium: 122, phosphorus: 77, energy: 48, tags: ["protein", "poultry", "lean"], sourcePage: 129 },
  { name: "鸡腿", category: "家禽类", portion: "45g", protein: 7, sodium: 26, potassium: 103, phosphorus: 73, energy: 77, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "兔肉", category: "家禽类", portion: "35g", protein: 7, sodium: 16, potassium: 101, phosphorus: 59, energy: 36, tags: ["protein", "poultry", "lean"], sourcePage: 129 },
  { name: "鸭肝", category: "家禽类", portion: "40g", protein: 6, sodium: 24, potassium: 111, phosphorus: 52, energy: 36, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "大米", category: "谷类主食", portion: "20g", protein: 1, sodium: 1, potassium: 21, phosphorus: 22, energy: 69, tags: ["grain", "lowK"], sourcePage: 130 },
  { name: "高粱米", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 56, phosphorus: 66, energy: 70, tags: ["grain"], sourcePage: 130 },
  { name: "挂面", category: "谷类主食", portion: "20g", protein: 2, sodium: 22, potassium: 24, phosphorus: 22, energy: 69, tags: ["grain"], sourcePage: 130 },
  { name: "河粉", category: "谷类主食", portion: "20g", protein: 2, sodium: 2, potassium: 17, phosphorus: 21, energy: 71, tags: ["grain", "lowK"], sourcePage: 130 },
  { name: "米粉", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 9, phosphorus: 11, energy: 69, tags: ["grain", "lowK"], sourcePage: 130 },
  { name: "糯米", category: "谷类主食", portion: "20g", protein: 1, sodium: 0, potassium: 27, phosphorus: 23, energy: 70, tags: ["grain"], sourcePage: 130 },
  { name: "芹麦", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 80, phosphorus: 59, energy: 65, tags: ["grain"], sourcePage: 130 },
  { name: "切面", category: "谷类主食", portion: "25g", protein: 2, sodium: 0, potassium: 26, phosphorus: 23, energy: 71, tags: ["grain"], sourcePage: 130 },
  { name: "通心粉", category: "谷类主食", portion: "20g", protein: 2, sodium: 7, potassium: 42, phosphorus: 19, energy: 70, tags: ["grain"], sourcePage: 130 },
  { name: "小米", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 57, phosphorus: 46, energy: 72, tags: ["grain"], sourcePage: 130 },
  { name: "玉米面", category: "谷类主食", portion: "20g", protein: 2, sodium: 0, potassium: 50, phosphorus: 39, energy: 68, tags: ["grain"], sourcePage: 131 },
  { name: "赤豆粽", category: "谷类主食", portion: "30g", protein: 1, sodium: 0, potassium: 21, phosphorus: 17, energy: 67, tags: ["grain"], sourcePage: 131 },
  { name: "豆沙大包", category: "谷类主食", portion: "25g", protein: 2, sodium: 0, potassium: 40, phosphorus: 24, energy: 71, tags: ["grain"], sourcePage: 131 },
  { name: "牛肉包", category: "谷类主食", portion: "35g", protein: 3, sodium: 112, potassium: 105, phosphorus: 41, energy: 79, tags: ["grain", "highNa"], sourcePage: 131 },
  { name: "牛肉水饺", category: "谷类主食", portion: "60g", protein: 5, sodium: 14, potassium: 85, phosphorus: 54, energy: 93, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉馄饨", category: "谷类主食", portion: "50g", protein: 4, sodium: 493, potassium: 55, phosphorus: 46, energy: 120, tags: ["grain", "veryHighNa"], sourcePage: 131 },
  { name: "芝麻汤团", category: "谷类主食", portion: "40g", protein: 1, sodium: 0, potassium: 14, phosphorus: 0, energy: 85, tags: ["grain"], sourcePage: 132 },
  { name: "米饭", category: "谷类主食", portion: "60g", protein: 2, sodium: 2, potassium: 23, phosphorus: 37, energy: 70, tags: ["grain"], sourcePage: 132 },
  { name: "米粥", category: "谷类主食", portion: "150g", protein: 2, sodium: 4, potassium: 20, phosphorus: 30, energy: 69, tags: ["grain", "liquid"], sourcePage: 132 },
  { name: "咸烧饼", category: "谷类主食", portion: "20g", protein: 2, sodium: 400, potassium: 39, phosphorus: 38, energy: 72, tags: ["grain", "veryHighNa"], sourcePage: 132 },
  { name: "油条", category: "谷类主食", portion: "30g", protein: 2, sodium: 176, potassium: 68, phosphorus: 23, energy: 116, tags: ["grain"], sourcePage: 132 },
  { name: "冬笋", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 14, energy: 10, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "栗子干", category: "蔬菜-低钾", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 17, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "西兰花", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 5, potassium: 4, phosphorus: 18, energy: 8, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "鲜香菇", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 1, potassium: 10, phosphorus: 27, energy: 10, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "青菜", category: "蔬菜-低钾", portion: "75g", protein: 1, sodium: 54, potassium: 11, phosphorus: 25, energy: 10, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "圆萝卜", category: "蔬菜-低钾", portion: "100g", protein: 1, sodium: 55, potassium: 60, phosphorus: 27, energy: 17, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "胡萝卜", category: "蔬菜-低钾", portion: "75g", protein: 1, sodium: 68, potassium: 68, phosphorus: 20, energy: 25, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "芹菜叶", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 42, potassium: 69, phosphorus: 32, energy: 16, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "丝瓜", category: "蔬菜-低钾", portion: "100g", protein: 1, sodium: 1, potassium: 76, phosphorus: 18, energy: 16, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "蒜苔", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 4, potassium: 84, phosphorus: 29, energy: 11, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "茭白", category: "蔬菜-中钾", portion: "100g", protein: 1, sodium: 16, potassium: 197, phosphorus: 33, energy: 21, tags: ["vegetable", "moderateK"], sourcePage: 137 },
  { name: "茄子", category: "蔬菜-中钾", portion: "100g", protein: 1, sodium: 6, potassium: 102, phosphorus: 38, energy: 17, tags: ["vegetable", "moderateK"], sourcePage: 135 },
  { name: "绿豆芽", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 16, potassium: 104, phosphorus: 30, energy: 13, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "木耳菜", category: "蔬菜-中钾", portion: "75g", protein: 1, sodium: 35, potassium: 105, phosphorus: 32, energy: 15, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "芋头", category: "蔬菜-中钾", portion: "30g", protein: 1, sodium: 10, potassium: 113, phosphorus: 17, energy: 24, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "菜心", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 13, potassium: 118, phosphorus: 27, energy: 13, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "西葫芦", category: "蔬菜-中钾", portion: "150g", protein: 1, sodium: 8, potassium: 138, phosphorus: 26, energy: 27, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "平菇", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 2, potassium: 129, phosphorus: 43, energy: 10, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "芹菜茎", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 159, potassium: 206, phosphorus: 38, energy: 20, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "生菜", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 42, potassium: 211, phosphorus: 35, energy: 11, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "海带", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 108, potassium: 222, phosphorus: 29, energy: 14, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "番茄", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 3, potassium: 233, phosphorus: 26, energy: 17, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "苦瓜", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 3, potassium: 256, phosphorus: 35, energy: 19, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "菠菜", category: "蔬菜-高钾", portion: "50g", protein: 1, sodium: 30, potassium: 488, phosphorus: 24, energy: 8, tags: ["vegetable", "veryHighK"], sourcePage: 138 },
  { name: "卷心菜", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 6, potassium: 766, phosphorus: 48, energy: 21, tags: ["vegetable", "veryHighK"], sourcePage: 138 },
  { name: "圆辣椒", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 3, potassium: 839, phosphorus: 26, energy: 18, tags: ["vegetable", "veryHighK"], sourcePage: 138 },
  { name: "杏仁椰汁", category: "水果-低钾", portion: "165g", protein: 1, sodium: 0, potassium: 0, phosphorus: 17, energy: 64, tags: ["fruit", "lowK"], sourcePage: 139 },
  { name: "芒果汁", category: "水果-低钾", portion: "125g", protein: 0, sodium: 26, potassium: 4, phosphorus: 3, energy: 55, tags: ["fruit", "lowK", "juice"], sourcePage: 139 },
  { name: "苹果", category: "水果-低钾", portion: "110g", protein: 0, sodium: 1, potassium: 91, phosphorus: 15, energy: 59, tags: ["fruit", "lowK"], sourcePage: 139 },
  { name: "香梨", category: "水果-低钾", portion: "110g", protein: 0, sodium: 1, potassium: 99, phosphorus: 34, energy: 51, tags: ["fruit", "lowK"], sourcePage: 139 },
  { name: "青苹果", category: "水果-低钾", portion: "120g", protein: 0, sodium: 2, potassium: 100, phosphorus: 8, energy: 59, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "鸭梨", category: "水果-低钾", portion: "150g", protein: 0, sodium: 2, potassium: 116, phosphorus: 21, energy: 65, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "椰子汁", category: "水果-低钾", portion: "230g", protein: 2, sodium: 32, potassium: 122, phosphorus: 25, energy: 117, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "芭桃", category: "水果-低钾", portion: "90g", protein: 1, sodium: 2, potassium: 136, phosphorus: 22, energy: 63, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "西瓜", category: "水果-中钾", portion: "180g", protein: 1, sodium: 6, potassium: 157, phosphorus: 16, energy: 45, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "桔", category: "水果-中钾", portion: "120g", protein: 1, sodium: 1, potassium: 157, phosphorus: 26, energy: 68, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "草莓", category: "水果-中钾", portion: "150g", protein: 1, sodium: 1, potassium: 170, phosphorus: 14, energy: 62, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "桃", category: "水果-中钾", portion: "130g", protein: 1, sodium: 7, potassium: 216, phosphorus: 26, energy: 62, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "鲜桂圆", category: "水果-中钾", portion: "90g", protein: 1, sodium: 4, potassium: 223, phosphorus: 27, energy: 63, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "葡萄", category: "水果-高钾", portion: "170g", protein: 1, sodium: 0, potassium: 0, phosphorus: 8, energy: 68, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "蜜桃", category: "水果-高钾", portion: "150g", protein: 1, sodium: 4, potassium: 254, phosphorus: 32, energy: 62, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "李", category: "水果-高钾", portion: "190g", protein: 1, sodium: 7, potassium: 274, phosphorus: 21, energy: 68, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "芒果", category: "水果-高钾", portion: "200g", protein: 1, sodium: 6, potassium: 276, phosphorus: 22, energy: 64, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "杨桃", category: "水果-高钾", portion: "240g", protein: 1, sodium: 3, potassium: 307, phosphorus: 43, energy: 70, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "草莓250g", category: "水果-高钾", portion: "250g", protein: 3, sodium: 11, potassium: 328, phosphorus: 68, energy: 75, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "西柚汁", category: "水果-高钾", portion: "205g", protein: 1, sodium: 17, potassium: 390, phosphorus: 39, energy: 70, tags: ["fruit", "highK", "juice"], sourcePage: 141 },
  { name: "白瓜", category: "水果-高钾", portion: "850g", protein: 8, sodium: 9, potassium: 595, phosphorus: 94, energy: 85, tags: ["fruit", "veryHighK"], sourcePage: 141 },
  { name: "柠檬", category: "水果-高钾", portion: "300g", protein: 3, sodium: 3, potassium: 627, phosphorus: 66, energy: 105, tags: ["fruit", "veryHighK"], sourcePage: 141 },
  { name: "芝麻油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "玉米油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 1, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "大豆油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "菜花籽油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "牛油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "黄油", category: "油脂", portion: "5g", protein: 0, sodium: 2, potassium: 2, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "花生酱", category: "油脂", portion: "7g", protein: 2, sodium: 35, potassium: 44, phosphorus: 28, energy: 45, tags: ["oil", "higherP"], sourcePage: 142 },
  { name: "巧克力花生酱", category: "油脂", portion: "7g", protein: 1, sodium: 15, potassium: 15, phosphorus: 16, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "芝麻酱", category: "油脂", portion: "7g", protein: 1, sodium: 0, potassium: 28, phosphorus: 13, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "千岛沙拉酱", category: "油脂", portion: "9g", protein: 0, sodium: 60, potassium: 12, phosphorus: 3, energy: 45, tags: ["oil", "highNa"], sourcePage: 142 },
  { name: "沙拉酱", category: "油脂", portion: "6g", protein: 0, sodium: 46, potassium: 10, phosphorus: 4, energy: 45, tags: ["oil"], sourcePage: 143 },
  { name: "大米淀粉", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 2, potassium: 0, phosphorus: 3, energy: 55, tags: ["lps", "lowK", "lowP"], sourcePage: 144 },
  { name: "小麦淀粉", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 0, potassium: 1, phosphorus: 5, energy: 53, tags: ["lps", "lowK", "lowP"], sourcePage: 144 },
  { name: "甘薯淀粉", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 1, potassium: 1, phosphorus: 3, energy: 68, tags: ["lps", "lowK"], sourcePage: 144 },
  { name: "玉米淀粉", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 1, potassium: 2, phosphorus: 5, energy: 69, tags: ["lps", "lowK", "lowP"], sourcePage: 144 },
  { name: "西米", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 60, tags: ["lps", "veryLowMineral"], sourcePage: 144 },
  { name: "凉粉", category: "低蛋白淀粉", portion: "180g", protein: 0, sodium: 5, potassium: 9, phosphorus: 2, energy: 67, tags: ["lps", "veryLowMineral"], sourcePage: 144 },
  { name: "粉丝", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 1.4, potassium: 3, phosphorus: 2, energy: 50, tags: ["lps", "veryLowMineral"], sourcePage: 144 },
  { name: "苹果酱", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 2, potassium: 6, phosphorus: 1, energy: 60, tags: ["lps"], sourcePage: 144 },
  { name: "杏酱", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 1, potassium: 24, phosphorus: 1, energy: 61, tags: ["lps"], sourcePage: 144 },
  { name: "蜂蜜", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 0.1, potassium: 5.6, phosphorus: 0.6, energy: 64, tags: ["lps"], sourcePage: 145 },
  { name: "冰糖", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 0.4, potassium: 0.2, phosphorus: 0, energy: 60, tags: ["lps", "veryLowMineral"], sourcePage: 145 },
  { name: "白砂糖", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 0.1, potassium: 0.8, phosphorus: 1.2, energy: 60, tags: ["lps", "veryLowMineral"], sourcePage: 145 },
  { name: "果冻", category: "低蛋白淀粉", portion: "60g", protein: 0, sodium: 19, potassium: 21, phosphorus: 13, energy: 64, tags: ["lps"], sourcePage: 145 },
  { name: "葡萄干", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 4, potassium: 182, phosphorus: 17, energy: 63, tags: ["lps", "highK"], sourcePage: 145 },
  { name: "黄豆酱油", category: "调味品", portion: "4g", protein: 0, sodium: 200, potassium: 14, phosphorus: 3, energy: 1, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "老抽", category: "调味品", portion: "3g", protein: 0, sodium: 200, potassium: 13, phosphorus: 5, energy: 4, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "生抽", category: "调味品", portion: "3g", protein: 0, sodium: 200, potassium: 11, phosphorus: 2, energy: 1, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "海鲜酱", category: "调味品", portion: "9g", protein: 0, sodium: 200, potassium: 29, phosphorus: 11, energy: 47, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "牛肉酱", category: "调味品", portion: "16g", protein: 0, sodium: 200, potassium: 31, phosphorus: 7, energy: 77, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "番茄沙司", category: "调味品", portion: "19g", protein: 0, sodium: 200, potassium: 62, phosphorus: 3, energy: 21, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "鸡精", category: "调味品", portion: "1g", protein: 0, sodium: 200, potassium: 1, phosphorus: 1, energy: 9, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "料酒", category: "调味品", portion: "74g", protein: 0, sodium: 200, potassium: 0, phosphorus: 0, energy: 1, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "味精", category: "调味品", portion: "1g", protein: 0, sodium: 200, potassium: 0, phosphorus: 0, energy: 3, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "盐", category: "调味品", portion: "0.5g", protein: 0, sodium: 200, potassium: 0, phosphorus: 0, energy: 0, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "均值乳制品", category: "乳制品", portion: "120ml", protein: 4, sodium: 64, potassium: 135, phosphorus: 119, energy: 75, tags: ["dairy"], sourcePage: 123 },
  { name: "鲜赤贝", category: "水产", portion: "50g", protein: 7, sodium: 133, potassium: 77, phosphorus: 59, energy: 31, tags: ["protein", "fish"], sourcePage: 127 },
  { name: "小黄鱼", category: "水产", portion: "40g", protein: 7, sodium: 41, potassium: 91, phosphorus: 75, energy: 40, tags: ["protein", "fish"], sourcePage: 127 },
  { name: "鲈鱼", category: "水产", portion: "30g", protein: 6, sodium: 39, potassium: 96, phosphorus: 70, energy: 26, tags: ["protein", "fish"], sourcePage: 127 },
  { name: "胖头鱼", category: "水产", portion: "45g", protein: 7, sodium: 27, potassium: 103, phosphorus: 81, energy: 45, tags: ["protein", "fish"], sourcePage: 127 },
  { name: "水浸鱿鱼", category: "水产", portion: "35g", protein: 6, sodium: 47, potassium: 6, phosphorus: 21, energy: 26, tags: ["protein", "fish", "lowK"], sourcePage: 127 },
  { name: "鱼片干", category: "水产", portion: "15g", protein: 7, sodium: 348, potassium: 38, phosphorus: 46, energy: 45, tags: ["protein", "fish", "highNa"], sourcePage: 127 },
  { name: "鲴鱼", category: "水产", portion: "35g", protein: 7, sodium: 39, potassium: 241, phosphorus: 130, energy: 35, tags: ["protein", "fish", "highK", "highP"], sourcePage: 127 },
  { name: "鸡肫", category: "家禽类", portion: "40g", protein: 7, sodium: 20, potassium: 82, phosphorus: 65, energy: 78, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸡翅", category: "家禽类", portion: "40g", protein: 7, sodium: 20, potassium: 82, phosphorus: 65, energy: 78, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸡爪", category: "家禽类", portion: "30g", protein: 7, sodium: 51, potassium: 32, phosphorus: 22, energy: 74, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸡肝", category: "家禽类", portion: "40g", protein: 7, sodium: 343, potassium: 87, phosphorus: 52, energy: 99, tags: ["protein", "poultry", "highNa"], sourcePage: 129 },
  { name: "烤鸡", category: "家禽类", portion: "30g", protein: 7, sodium: 142, potassium: 44, phosphorus: 43, energy: 75, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "土鸡", category: "家禽类", portion: "30g", protein: 6, sodium: 22, potassium: 89, phosphorus: 46, energy: 40, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "乌骨鸡", category: "家禽类", portion: "30g", protein: 7, sodium: 19, potassium: 101, phosphorus: 66, energy: 35, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸭", category: "家禽类", portion: "45g", protein: 7, sodium: 31, potassium: 86, phosphorus: 55, energy: 108, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "野兔肉", category: "家禽类", portion: "40g", protein: 7, sodium: 35, potassium: 156, phosphorus: 123, energy: 35, tags: ["protein", "poultry", "highP"], sourcePage: 129 },
  { name: "黑米", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 51, phosphorus: 71, energy: 67, tags: ["grain"], sourcePage: 130 },
  { name: "苦荞麦粉", category: "谷类主食", portion: "25g", protein: 2, sodium: 1, potassium: 80, phosphorus: 61, energy: 76, tags: ["grain"], sourcePage: 130 },
  { name: "面粉", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 26, phosphorus: 23, energy: 70, tags: ["grain"], sourcePage: 130 },
  { name: "年糕", category: "谷类主食", portion: "40g", protein: 1, sodium: 23, potassium: 32, phosphorus: 21, energy: 62, tags: ["grain"], sourcePage: 130 },
  { name: "燕麦片", category: "谷类主食", portion: "25g", protein: 4, sodium: 1, potassium: 54, phosphorus: 73, energy: 92, tags: ["grain"], sourcePage: 130 },
  { name: "薏米", category: "谷类主食", portion: "20g", protein: 3, sodium: 1, potassium: 48, phosphorus: 43, energy: 71, tags: ["grain"], sourcePage: 130 },
  { name: "玉米(干)", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 60, phosphorus: 44, energy: 67, tags: ["grain"], sourcePage: 131 },
  { name: "玉米(鲜)", category: "谷类主食", portion: "75g", protein: 3, sodium: 1, potassium: 179, phosphorus: 88, energy: 80, tags: ["grain"], sourcePage: 131 },
  { name: "菜肉馄饨", category: "谷类主食", portion: "50g", protein: 3, sodium: 18, potassium: 51, phosphorus: 43, energy: 113, tags: ["grain"], sourcePage: 131 },
  { name: "菜肉水饺", category: "谷类主食", portion: "45g", protein: 3, sodium: 11, potassium: 59, phosphorus: 52, energy: 96, tags: ["grain"], sourcePage: 131 },
  { name: "叉烧包", category: "谷类主食", portion: "35g", protein: 3, sodium: 93, potassium: 70, phosphorus: 40, energy: 85, tags: ["grain"], sourcePage: 131 },
  { name: "春卷", category: "谷类主食", portion: "40g", protein: 2, sodium: 194, potassium: 36, phosphorus: 38, energy: 185, tags: ["grain", "highNa"], sourcePage: 131 },
  { name: "豆沙汤团", category: "谷类主食", portion: "30g", protein: 1, sodium: 0, potassium: 33, phosphorus: 18, energy: 61, tags: ["grain"], sourcePage: 131 },
  { name: "烧卖", category: "谷类主食", portion: "45g", protein: 2, sodium: 61, potassium: 27, phosphorus: 19, energy: 115, tags: ["grain"], sourcePage: 131 },
  { name: "生煎", category: "谷类主食", portion: "40g", protein: 3, sodium: 136, potassium: 43, phosphorus: 36, energy: 93, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉大包", category: "谷类主食", portion: "40g", protein: 3, sodium: 185, potassium: 46, phosphorus: 36, energy: 94, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉锅贴", category: "谷类主食", portion: "45g", protein: 4, sodium: 2, potassium: 59, phosphorus: 50, energy: 113, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉水饺", category: "谷类主食", portion: "60g", protein: 4, sodium: 15, potassium: 74, phosphorus: 51, energy: 131, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉汤团", category: "谷类主食", portion: "40g", protein: 2, sodium: 68, potassium: 33, phosphorus: 29, energy: 92, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉粽", category: "谷类主食", portion: "30g", protein: 2, sodium: 31, potassium: 55, phosphorus: 30, energy: 70, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉月饼", category: "谷类主食", portion: "30g", protein: 3, sodium: 5, potassium: 57, phosphorus: 41, energy: 127, tags: ["grain"], sourcePage: 131 },
  { name: "香菇菜包", category: "谷类主食", portion: "40g", protein: 3, sodium: 189, potassium: 37, phosphorus: 31, energy: 72, tags: ["grain"], sourcePage: 131 },
  { name: "小笼馒头", category: "谷类主食", portion: "45g", protein: 4, sodium: 339, potassium: 62, phosphorus: 45, energy: 112, tags: ["grain", "highNa"], sourcePage: 131 },
  { name: "花卷", category: "谷类主食", portion: "30g", protein: 2, sodium: 29, potassium: 25, phosphorus: 22, energy: 65, tags: ["grain"], sourcePage: 132 },
  { name: "馒头", category: "谷类主食", portion: "20g", protein: 2, sodium: 0, potassium: 37, phosphorus: 36, energy: 68, tags: ["grain"], sourcePage: 132 },
  { name: "切片面包", category: "谷类主食", portion: "30g", protein: 2, sodium: 1, potassium: 20, phosphorus: 19, energy: 79, tags: ["grain"], sourcePage: 132 },
  { name: "小餐包", category: "谷类主食", portion: "30g", protein: 2, sodium: 1, potassium: 20, phosphorus: 19, energy: 79, tags: ["grain"], sourcePage: 132 },
  { name: "煮面条", category: "谷类主食", portion: "60g", protein: 2, sodium: 16, potassium: 9, phosphorus: 15, energy: 65, tags: ["grain"], sourcePage: 132 },
  { name: "谷类均值", category: "谷类主食", portion: "1份", protein: 2, sodium: 87, potassium: 44, phosphorus: 33, energy: 92, tags: ["grain"], sourcePage: 132 },
  { name: "马齿苋", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 0, potassium: 0, phosphorus: 28, energy: 14, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "牛蒡叶", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 15, energy: 9, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "野韭菜", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 12, energy: 9, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "野芜菜", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 23, energy: 15, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "菌陈蒿", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 24, energy: 14, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "草头", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 7, potassium: 8, phosphorus: 6, energy: 8, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "发菜(干)", category: "蔬菜-低钾", portion: "5g", protein: 1, sodium: 5, potassium: 11, phosphorus: 4, energy: 9, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "木耳(水发)", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 4, potassium: 26, phosphorus: 6, energy: 11, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "山药(干)", category: "蔬菜-低钾", portion: "10g", protein: 1, sodium: 10, potassium: 27, phosphorus: 2, energy: 32, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "金针菜", category: "蔬菜-低钾", portion: "5g", protein: 1, sodium: 3, potassium: 31, phosphorus: 11, energy: 10, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "甘薯", category: "蔬菜-低钾", portion: "25g", protein: 0, sodium: 7, potassium: 33, phosphorus: 10, energy: 25, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "花菜", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 12, potassium: 35, phosphorus: 20, energy: 12, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "洋葱", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 2, potassium: 37, phosphorus: 17, energy: 23, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "韭菜", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 3, potassium: 38, phosphorus: 19, energy: 11, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "冬菇(干)", category: "蔬菜-低钾", portion: "5g", protein: 1, sodium: 1, potassium: 58, phosphorus: 23, energy: 11, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "黄瓜", category: "蔬菜-低钾", portion: "150g", protein: 1, sodium: 21, potassium: 89, phosphorus: 33, energy: 17, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "草菇", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 37, potassium: 90, phosphorus: 17, energy: 12, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "豆瓣菜", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 31, potassium: 90, phosphorus: 13, energy: 9, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "蒜头", category: "蔬菜-低钾", portion: "20g", protein: 1, sodium: 2, potassium: 92, phosphorus: 42, energy: 26, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "油菜", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 28, potassium: 105, phosphorus: 20, energy: 12, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "空心菜", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 99, potassium: 107, phosphorus: 24, energy: 11, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "毛笋", category: "蔬菜-中钾", portion: "50g", protein: 2, sodium: 0, potassium: 110, phosphorus: 19, energy: 10, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "芥菜头", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 33, potassium: 122, phosphorus: 18, energy: 17, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "荸荠", category: "蔬菜-中钾", portion: "40g", protein: 0, sodium: 6, potassium: 122, phosphorus: 18, energy: 24, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "黄苔叶", category: "蔬菜-中钾", portion: "75g", protein: 1, sodium: 27, potassium: 124, phosphorus: 22, energy: 14, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "水发黄蘑", category: "蔬菜-中钾", portion: "25g", protein: 1, sodium: 0, potassium: 128, phosphorus: 13, energy: 5, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "雪里蕻", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 15, potassium: 141, phosphorus: 24, energy: 12, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "冬瓜", category: "蔬菜-高钾", portion: "200g", protein: 1, sodium: 2, potassium: 228, phosphorus: 24, energy: 18, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "甜菜叶", category: "蔬菜-高钾", portion: "50g", protein: 1, sodium: 101, potassium: 274, phosphorus: 20, energy: 10, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "菊苣", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 22, potassium: 314, phosphorus: 28, energy: 17, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "长萝卜", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 63, potassium: 449, phosphorus: 17, energy: 17, tags: ["vegetable", "veryHighK"], sourcePage: 138 },
  { name: "杏仁露", category: "水果-低钾", portion: "185g", protein: 2, sodium: 17, potassium: 2, phosphorus: 2, energy: 85, tags: ["fruit", "lowK"], sourcePage: 139 },
  { name: "无核黑枣", category: "水果-低钾", portion: "25g", protein: 0, sodium: 2, potassium: 120, phosphorus: 16, energy: 57, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "柿", category: "水果-低钾", portion: "80g", protein: 0, sodium: 1, potassium: 121, phosphorus: 18, energy: 57, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "菠萝", category: "水果-中钾", portion: "150g", protein: 1, sodium: 1, potassium: 170, phosphorus: 14, energy: 62, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "红富士苹果", category: "水果-中钾", portion: "150g", protein: 1, sodium: 1, potassium: 173, phosphorus: 17, energy: 68, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "金橘", category: "水果-中钾", portion: "120g", protein: 1, sodium: 4, potassium: 173, phosphorus: 24, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "猕猴桃", category: "水果-中钾", portion: "120g", protein: 1, sodium: 12, potassium: 173, phosphorus: 31, energy: 67, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "香蕉", category: "水果-中钾", portion: "70g", protein: 1, sodium: 1, potassium: 179, phosphorus: 20, energy: 64, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "鲜枣", category: "水果-中钾", portion: "50g", protein: 1, sodium: 1, potassium: 188, phosphorus: 12, energy: 61, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "柚", category: "水果-中钾", portion: "160g", protein: 1, sodium: 5, potassium: 190, phosphorus: 38, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "山楂", category: "水果-中钾", portion: "65g", protein: 0, sodium: 4, potassium: 194, phosphorus: 16, energy: 62, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "柑", category: "水果-中钾", portion: "130g", protein: 1, sodium: 2, potassium: 200, phosphorus: 23, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "橙汁", category: "水果-中钾", portion: "135g", protein: 1, sodium: 4, potassium: 203, phosphorus: 18, energy: 62, tags: ["fruit", "moderateK", "juice"], sourcePage: 140 },
  { name: "枇杷", category: "水果-中钾", portion: "170g", protein: 1, sodium: 7, potassium: 207, phosphorus: 14, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "石榴", category: "水果-中钾", portion: "100g", protein: 1, sodium: 1, potassium: 218, phosphorus: 76, energy: 64, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "橙", category: "水果-中钾", portion: "140g", protein: 1, sodium: 2, potassium: 223, phosphorus: 31, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "紫葡萄", category: "水果-中钾", portion: "150g", protein: 1, sodium: 3, potassium: 227, phosphorus: 15, energy: 65, tags: ["fruit", "moderateK"], sourcePage: 141 },
  { name: "椰子", category: "水果-中钾", portion: "50g", protein: 2, sodium: 28, potassium: 238, phosphorus: 45, energy: 116, tags: ["fruit", "moderateK"], sourcePage: 141 },
];
