window.FOOD_DATABASE = [
  { name: "全脂奶", category: "乳制品", portion: "130g", protein: 4, sodium: 32, potassium: 172, phosphorus: 113, energy: 79, tags: ["dairy", "moderateK"], sourcePage: 123 },
  { name: "脱脂酸奶", category: "乳制品", portion: "120g", protein: 4, sodium: 33, potassium: 187, phosphorus: 109, energy: 68, tags: ["dairy", "moderateK"], sourcePage: 123 },
  { name: "果粒酸奶", category: "乳制品", portion: "130g", protein: 4, sodium: 42, potassium: 144, phosphorus: 117, energy: 87, tags: ["dairy", "moderateK"], sourcePage: 123 },
  { name: "全脂奶粉", category: "乳制品", portion: "20g", protein: 4, sodium: 52, potassium: 89, phosphorus: 93, energy: 95, tags: ["dairy", "lowK"], sourcePage: 123 },
  { name: "低脂奶粉", category: "乳制品", portion: "15g", protein: 4, sodium: 60, potassium: 198, phosphorus: 141, energy: 63, tags: ["dairy", "highP"], sourcePage: 123 },
  { name: "酸奶", category: "乳制品", portion: "160g", protein: 4, sodium: 64, potassium: 240, phosphorus: 136, energy: 115, tags: ["dairy", "highK"], sourcePage: 123 },
  { name: "脱脂奶", category: "乳制品", portion: "140g", protein: 4, sodium: 164, potassium: 286, phosphorus: 134, energy: 46, tags: ["dairy", "highK"], sourcePage: 123 },
  { name: "低脂奶酪", category: "乳制品", portion: "20g", protein: 4, sodium: 337, potassium: 74, phosphorus: 121, energy: 48, tags: ["dairy", "highNa"], sourcePage: 123 },
  { name: "低脂奶", category: "乳制品", portion: "140g", protein: 4, sodium: 391, potassium: 259, phosphorus: 127, energy: 60, tags: ["dairy", "highNa"], sourcePage: 123 },
  { name: "奶酪", category: "乳制品", portion: "25g", protein: 4, sodium: 400, potassium: 79, phosphorus: 97, energy: 87, tags: ["dairy", "highNa", "highP"], sourcePage: 123 },
  { name: "鹌鹑蛋", category: "蛋类", portion: "55g", protein: 7, sodium: 59, potassium: 190, phosphorus: 98, energy: 88, tags: ["protein", "egg"], sourcePage: 124 },
  { name: "鸡蛋", category: "蛋类", portion: "60g", protein: 7, sodium: 54, potassium: 55, phosphorus: 78, energy: 117, tags: ["protein", "egg", "lowK"], sourcePage: 124 },
  { name: "鸡蛋清", category: "蛋类", portion: "80g", protein: 7, sodium: 62, potassium: 13, phosphorus: 9, energy: 38, tags: ["protein", "egg", "lowK", "lowP"], sourcePage: 124 },
  { name: "鸡蛋黄", category: "蛋类", portion: "45g", protein: 7, sodium: 11, potassium: 0, phosphorus: 23, energy: 146, tags: ["protein", "egg"], sourcePage: 124 },
  { name: "松花鸭蛋", category: "蛋类", portion: "50g", protein: 7, sodium: 271, potassium: 231, phosphorus: 83, energy: 86, tags: ["protein", "egg", "highNa"], sourcePage: 124 },
  { name: "咸鸭蛋", category: "蛋类", portion: "55g", protein: 7, sodium: 1488, potassium: 338, phosphorus: 127, energy: 435, tags: ["protein", "egg", "veryHighNa"], sourcePage: 124 },
  { name: "鸭蛋清", category: "蛋类", portion: "70g", protein: 7, sodium: 50, potassium: 71, phosphorus: 11, energy: 33, tags: ["protein", "egg", "lowP"], sourcePage: 124 },
  { name: "鲅鱼", category: "水产", portion: "30g", protein: 6, sodium: 22, potassium: 111, phosphorus: 39, energy: 37, tags: ["protein", "fish", "lowP"], sourcePage: 124 },
  { name: "白姑鱼", category: "水产", portion: "35g", protein: 7, sodium: 53, potassium: 134, phosphorus: 60, energy: 53, tags: ["protein", "fish"], sourcePage: 124 },
  { name: "白米虾", category: "水产", portion: "40g", protein: 7, sodium: 36, potassium: 102, phosphorus: 106, energy: 32, tags: ["protein", "fish", "highP"], sourcePage: 124 },
  { name: "草鱼", category: "水产", portion: "40g", protein: 7, sodium: 184, potassium: 125, phosphorus: 81, energy: 73, tags: ["protein", "fish"], sourcePage: 125 },
  { name: "鲳鱼", category: "水产", portion: "35g", protein: 6, sodium: 22, potassium: 115, phosphorus: 54, energy: 49, tags: ["protein", "fish", "lowP"], sourcePage: 125 },
  { name: "大黄鱼", category: "水产", portion: "40g", protein: 7, sodium: 48, potassium: 104, phosphorus: 70, energy: 59, tags: ["protein", "fish"], sourcePage: 125 },
  { name: "鲜淡菜", category: "水产", portion: "60g", protein: 7, sodium: 270, potassium: 94, phosphorus: 118, energy: 50, tags: ["protein", "fish", "highNa"], sourcePage: 125 },
  { name: "鲷鱼", category: "水产", portion: "40g", protein: 7, sodium: 42, potassium: 104, phosphorus: 121, energy: 74, tags: ["protein", "fish", "highP"], sourcePage: 125 },
  { name: "海蜇皮", category: "水产", portion: "180g", protein: 7, sodium: 585, potassium: 288, phosphorus: 54, energy: 40, tags: ["protein", "fish", "veryHighNa"], sourcePage: 125 },
  { name: "鲜扇贝", category: "水产", portion: "60g", protein: 7, sodium: 184, potassium: 581, phosphorus: 302, energy: 48, tags: ["protein", "fish", "veryHighK", "veryHighP"], sourcePage: 126 },
  { name: "银鱼", category: "水产", portion: "40g", protein: 7, sodium: 3, potassium: 98, phosphorus: 9, energy: 48, tags: ["protein", "fish", "lowP"], sourcePage: 127 },
  { name: "泥鳅", category: "水产", portion: "65g", protein: 7, sodium: 33, potassium: 443, phosphorus: 190, energy: 57, tags: ["protein", "fish", "highK", "highP"], sourcePage: 127 },
  { name: "方腿", category: "家畜类", portion: "45g", protein: 6, sodium: 170, potassium: 96, phosphorus: 87, energy: 51, tags: ["protein", "meat"], sourcePage: 127 },
  { name: "牛肉后腿", category: "家畜类", portion: "40g", protein: 6, sodium: 25, potassium: 85, phosphorus: 63, energy: 36, tags: ["protein", "meat", "lean"], sourcePage: 127 },
  { name: "牛肉前腿", category: "家畜类", portion: "45g", protein: 7, sodium: 25, potassium: 97, phosphorus: 71, energy: 42, tags: ["protein", "meat", "lean"], sourcePage: 127 },
  { name: "牛腱子", category: "家畜类", portion: "15g", protein: 7, sodium: 62, potassium: 78, phosphorus: 71, energy: 84, tags: ["protein", "meat"], sourcePage: 127 },
  { name: "羊肉瘦", category: "家畜类", portion: "35g", protein: 7, sodium: 24, potassium: 138, phosphorus: 67, energy: 40, tags: ["protein", "meat", "lean"], sourcePage: 128 },
  { name: "猪瘦肉", category: "家畜类", portion: "35g", protein: 7, sodium: 20, potassium: 105, phosphorus: 65, energy: 49, tags: ["protein", "meat", "lean"], sourcePage: 128 },
  { name: "猪后臀", category: "家畜类", portion: "40g", protein: 7, sodium: 31, potassium: 77, phosphorus: 58, energy: 131, tags: ["protein", "meat"], sourcePage: 128 },
  { name: "鹌鹑", category: "家禽类", portion: "35g", protein: 7, sodium: 17, potassium: 71, phosphorus: 62, energy: 38, tags: ["protein", "poultry", "lowK"], sourcePage: 128 },
  { name: "鸡", category: "家禽类", portion: "40g", protein: 7, sodium: 24, potassium: 91, phosphorus: 56, energy: 96, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸽", category: "家禽类", portion: "40g", protein: 7, sodium: 25, potassium: 142, phosphorus: 58, energy: 85, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸡胸肉", category: "家禽类", portion: "35g", protein: 8, sodium: 14, potassium: 122, phosphorus: 77, energy: 48, tags: ["protein", "poultry", "lean"], sourcePage: 129 },
  { name: "鸡腿", category: "家禽类", portion: "45g", protein: 7, sodium: 26, potassium: 103, phosphorus: 73, energy: 77, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "兔肉", category: "家禽类", portion: "35g", protein: 7, sodium: 16, potassium: 101, phosphorus: 59, energy: 36, tags: ["protein", "poultry", "lean"], sourcePage: 129 },
  { name: "鸭肝", category: "家禽类", portion: "40g", protein: 6, sodium: 24, potassium: 111, phosphorus: 52, energy: 36, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "大米", category: "谷类主食", portion: "20g", protein: 1, sodium: 1, potassium: 21, phosphorus: 22, energy: 69, tags: ["grain", "lowK"], sourcePage: 130 },
  { name: "高粱米", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 56, phosphorus: 66, energy: 70, tags: ["grain"], sourcePage: 130 },
  { name: "挂面", category: "谷类主食", portion: "20g", protein: 2, sodium: 22, potassium: 24, phosphorus: 22, energy: 69, tags: ["grain"], sourcePage: 130 },
  { name: "河粉", category: "谷类主食", portion: "20g", protein: 2, sodium: 2, potassium: 17, phosphorus: 21, energy: 71, tags: ["grain", "lowK"], sourcePage: 130 },
  { name: "米粉", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 9, phosphorus: 11, energy: 69, tags: ["grain", "lowK"], sourcePage: 130 },
  { name: "糯米", category: "谷类主食", portion: "20g", protein: 1, sodium: 0, potassium: 27, phosphorus: 23, energy: 70, tags: ["grain"], sourcePage: 130 },
  { name: "芹麦", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 80, phosphorus: 59, energy: 65, tags: ["grain"], sourcePage: 130 },
  { name: "切面", category: "谷类主食", portion: "25g", protein: 2, sodium: 0, potassium: 26, phosphorus: 23, energy: 71, tags: ["grain"], sourcePage: 130 },
  { name: "通心粉", category: "谷类主食", portion: "20g", protein: 2, sodium: 7, potassium: 42, phosphorus: 19, energy: 70, tags: ["grain"], sourcePage: 130 },
  { name: "小米", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 57, phosphorus: 46, energy: 72, tags: ["grain"], sourcePage: 130 },
  { name: "玉米面", category: "谷类主食", portion: "20g", protein: 2, sodium: 0, potassium: 50, phosphorus: 39, energy: 68, tags: ["grain"], sourcePage: 131 },
  { name: "赤豆粽", category: "谷类主食", portion: "30g", protein: 1, sodium: 0, potassium: 21, phosphorus: 17, energy: 67, tags: ["grain"], sourcePage: 131 },
  { name: "豆沙大包", category: "谷类主食", portion: "25g", protein: 2, sodium: 0, potassium: 40, phosphorus: 24, energy: 71, tags: ["grain"], sourcePage: 131 },
  { name: "牛肉包", category: "谷类主食", portion: "35g", protein: 3, sodium: 112, potassium: 105, phosphorus: 41, energy: 79, tags: ["grain", "highNa"], sourcePage: 131 },
  { name: "牛肉水饺", category: "谷类主食", portion: "60g", protein: 5, sodium: 14, potassium: 85, phosphorus: 54, energy: 93, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉馄饨", category: "谷类主食", portion: "50g", protein: 4, sodium: 493, potassium: 55, phosphorus: 46, energy: 120, tags: ["grain", "veryHighNa"], sourcePage: 131 },
  { name: "芝麻汤团", category: "谷类主食", portion: "40g", protein: 1, sodium: 0, potassium: 14, phosphorus: 0, energy: 85, tags: ["grain"], sourcePage: 132 },
  { name: "米饭", category: "谷类主食", portion: "60g", protein: 2, sodium: 2, potassium: 23, phosphorus: 37, energy: 70, tags: ["grain"], sourcePage: 132 },
  { name: "米粥", category: "谷类主食", portion: "150g", protein: 2, sodium: 4, potassium: 20, phosphorus: 30, energy: 69, tags: ["grain", "liquid"], sourcePage: 132 },
  { name: "咸烧饼", category: "谷类主食", portion: "20g", protein: 2, sodium: 400, potassium: 39, phosphorus: 38, energy: 72, tags: ["grain", "veryHighNa"], sourcePage: 132 },
  { name: "油条", category: "谷类主食", portion: "30g", protein: 2, sodium: 176, potassium: 68, phosphorus: 23, energy: 116, tags: ["grain"], sourcePage: 132 },
  { name: "冬笋", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 14, energy: 10, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "栗子干", category: "蔬菜-低钾", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 17, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "西兰花", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 5, potassium: 4, phosphorus: 18, energy: 8, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "鲜香菇", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 1, potassium: 10, phosphorus: 27, energy: 10, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "青菜", category: "蔬菜-低钾", portion: "75g", protein: 1, sodium: 54, potassium: 11, phosphorus: 25, energy: 10, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "圆萝卜", category: "蔬菜-低钾", portion: "100g", protein: 1, sodium: 55, potassium: 60, phosphorus: 27, energy: 17, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "胡萝卜", category: "蔬菜-低钾", portion: "75g", protein: 1, sodium: 68, potassium: 68, phosphorus: 20, energy: 25, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "芹菜叶", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 42, potassium: 69, phosphorus: 32, energy: 16, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "丝瓜", category: "蔬菜-低钾", portion: "100g", protein: 1, sodium: 1, potassium: 76, phosphorus: 18, energy: 16, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "蒜苔", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 4, potassium: 84, phosphorus: 29, energy: 11, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "茭白", category: "蔬菜-中钾", portion: "100g", protein: 1, sodium: 16, potassium: 197, phosphorus: 33, energy: 21, tags: ["vegetable", "moderateK"], sourcePage: 137 },
  { name: "茄子", category: "蔬菜-中钾", portion: "100g", protein: 1, sodium: 6, potassium: 102, phosphorus: 38, energy: 17, tags: ["vegetable", "moderateK"], sourcePage: 135 },
  { name: "绿豆芽", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 16, potassium: 104, phosphorus: 30, energy: 13, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "木耳菜", category: "蔬菜-中钾", portion: "75g", protein: 1, sodium: 35, potassium: 105, phosphorus: 32, energy: 15, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "芋头", category: "蔬菜-中钾", portion: "30g", protein: 1, sodium: 10, potassium: 113, phosphorus: 17, energy: 24, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "菜心", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 13, potassium: 118, phosphorus: 27, energy: 13, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "西葫芦", category: "蔬菜-中钾", portion: "150g", protein: 1, sodium: 8, potassium: 138, phosphorus: 26, energy: 27, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "平菇", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 2, potassium: 129, phosphorus: 43, energy: 10, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "芹菜茎", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 159, potassium: 206, phosphorus: 38, energy: 20, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "生菜", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 42, potassium: 211, phosphorus: 35, energy: 11, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "海带", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 108, potassium: 222, phosphorus: 29, energy: 14, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "番茄", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 3, potassium: 233, phosphorus: 26, energy: 17, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "苦瓜", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 3, potassium: 256, phosphorus: 35, energy: 19, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "菠菜", category: "蔬菜-高钾", portion: "50g", protein: 1, sodium: 30, potassium: 488, phosphorus: 24, energy: 8, tags: ["vegetable", "veryHighK"], sourcePage: 138 },
  { name: "卷心菜", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 6, potassium: 766, phosphorus: 48, energy: 21, tags: ["vegetable", "veryHighK"], sourcePage: 138 },
  { name: "圆辣椒", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 3, potassium: 839, phosphorus: 26, energy: 18, tags: ["vegetable", "veryHighK"], sourcePage: 138 },
  { name: "杏仁椰汁", category: "水果-低钾", portion: "165g", protein: 1, sodium: 0, potassium: 0, phosphorus: 17, energy: 64, tags: ["fruit", "lowK"], sourcePage: 139 },
  { name: "芒果汁", category: "水果-低钾", portion: "125g", protein: 0, sodium: 26, potassium: 4, phosphorus: 3, energy: 55, tags: ["fruit", "lowK", "juice"], sourcePage: 139 },
  { name: "苹果", category: "水果-低钾", portion: "110g", protein: 0, sodium: 1, potassium: 91, phosphorus: 15, energy: 59, tags: ["fruit", "lowK"], sourcePage: 139 },
  { name: "香梨", category: "水果-低钾", portion: "110g", protein: 0, sodium: 1, potassium: 99, phosphorus: 34, energy: 51, tags: ["fruit", "lowK"], sourcePage: 139 },
  { name: "青苹果", category: "水果-低钾", portion: "120g", protein: 0, sodium: 2, potassium: 100, phosphorus: 8, energy: 59, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "鸭梨", category: "水果-低钾", portion: "150g", protein: 0, sodium: 2, potassium: 116, phosphorus: 21, energy: 65, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "椰子汁", category: "水果-低钾", portion: "230g", protein: 2, sodium: 32, potassium: 122, phosphorus: 25, energy: 117, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "芭桃", category: "水果-低钾", portion: "90g", protein: 1, sodium: 2, potassium: 136, phosphorus: 22, energy: 63, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "西瓜", category: "水果-中钾", portion: "180g", protein: 1, sodium: 6, potassium: 157, phosphorus: 16, energy: 45, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "桔", category: "水果-中钾", portion: "120g", protein: 1, sodium: 1, potassium: 157, phosphorus: 26, energy: 68, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "草莓", category: "水果-中钾", portion: "150g", protein: 1, sodium: 1, potassium: 170, phosphorus: 14, energy: 62, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "桃", category: "水果-中钾", portion: "130g", protein: 1, sodium: 7, potassium: 216, phosphorus: 26, energy: 62, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "鲜桂圆", category: "水果-中钾", portion: "90g", protein: 1, sodium: 4, potassium: 223, phosphorus: 27, energy: 63, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "葡萄", category: "水果-高钾", portion: "170g", protein: 1, sodium: 0, potassium: 0, phosphorus: 8, energy: 68, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "蜜桃", category: "水果-高钾", portion: "150g", protein: 1, sodium: 4, potassium: 254, phosphorus: 32, energy: 62, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "李", category: "水果-高钾", portion: "190g", protein: 1, sodium: 7, potassium: 274, phosphorus: 21, energy: 68, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "芒果", category: "水果-高钾", portion: "200g", protein: 1, sodium: 6, potassium: 276, phosphorus: 22, energy: 64, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "杨桃", category: "水果-高钾", portion: "240g", protein: 1, sodium: 3, potassium: 307, phosphorus: 43, energy: 70, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "草莓250g", category: "水果-高钾", portion: "250g", protein: 3, sodium: 11, potassium: 328, phosphorus: 68, energy: 75, tags: ["fruit", "highK"], sourcePage: 141 },
  { name: "西柚汁", category: "水果-高钾", portion: "205g", protein: 1, sodium: 17, potassium: 390, phosphorus: 39, energy: 70, tags: ["fruit", "highK", "juice"], sourcePage: 141 },
  { name: "白瓜", category: "水果-高钾", portion: "850g", protein: 8, sodium: 9, potassium: 595, phosphorus: 94, energy: 85, tags: ["fruit", "veryHighK"], sourcePage: 141 },
  { name: "柠檬", category: "水果-高钾", portion: "300g", protein: 3, sodium: 3, potassium: 627, phosphorus: 66, energy: 105, tags: ["fruit", "veryHighK"], sourcePage: 141 },
  { name: "芝麻油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "玉米油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 1, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "大豆油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "菜花籽油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "牛油", category: "油脂", portion: "5g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "黄油", category: "油脂", portion: "5g", protein: 0, sodium: 2, potassium: 2, phosphorus: 0, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "花生酱", category: "油脂", portion: "7g", protein: 2, sodium: 35, potassium: 44, phosphorus: 28, energy: 45, tags: ["oil", "higherP"], sourcePage: 142 },
  { name: "巧克力花生酱", category: "油脂", portion: "7g", protein: 1, sodium: 15, potassium: 15, phosphorus: 16, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "芝麻酱", category: "油脂", portion: "7g", protein: 1, sodium: 0, potassium: 28, phosphorus: 13, energy: 45, tags: ["oil"], sourcePage: 142 },
  { name: "千岛沙拉酱", category: "油脂", portion: "9g", protein: 0, sodium: 60, potassium: 12, phosphorus: 3, energy: 45, tags: ["oil", "highNa"], sourcePage: 142 },
  { name: "沙拉酱", category: "油脂", portion: "6g", protein: 0, sodium: 46, potassium: 10, phosphorus: 4, energy: 45, tags: ["oil"], sourcePage: 143 },
  { name: "大米淀粉", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 2, potassium: 0, phosphorus: 3, energy: 55, tags: ["lps", "lowK", "lowP"], sourcePage: 144 },
  { name: "小麦淀粉", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 0, potassium: 1, phosphorus: 5, energy: 53, tags: ["lps", "lowK", "lowP"], sourcePage: 144 },
  { name: "甘薯淀粉", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 1, potassium: 1, phosphorus: 3, energy: 68, tags: ["lps", "lowK"], sourcePage: 144 },
  { name: "玉米淀粉", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 1, potassium: 2, phosphorus: 5, energy: 69, tags: ["lps", "lowK", "lowP"], sourcePage: 144 },
  { name: "西米", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 0, potassium: 0, phosphorus: 0, energy: 60, tags: ["lps", "veryLowMineral"], sourcePage: 144 },
  { name: "凉粉", category: "低蛋白淀粉", portion: "180g", protein: 0, sodium: 5, potassium: 9, phosphorus: 2, energy: 67, tags: ["lps", "veryLowMineral"], sourcePage: 144 },
  { name: "粉丝", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 1.4, potassium: 3, phosphorus: 2, energy: 50, tags: ["lps", "veryLowMineral"], sourcePage: 144 },
  { name: "苹果酱", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 2, potassium: 6, phosphorus: 1, energy: 60, tags: ["lps"], sourcePage: 144 },
  { name: "杏酱", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 1, potassium: 24, phosphorus: 1, energy: 61, tags: ["lps"], sourcePage: 144 },
  { name: "蜂蜜", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 0.1, potassium: 5.6, phosphorus: 0.6, energy: 64, tags: ["lps"], sourcePage: 145 },
  { name: "冰糖", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 0.4, potassium: 0.2, phosphorus: 0, energy: 60, tags: ["lps", "veryLowMineral"], sourcePage: 145 },
  { name: "白砂糖", category: "低蛋白淀粉", portion: "15g", protein: 0, sodium: 0.1, potassium: 0.8, phosphorus: 1.2, energy: 60, tags: ["lps", "veryLowMineral"], sourcePage: 145 },
  { name: "果冻", category: "低蛋白淀粉", portion: "60g", protein: 0, sodium: 19, potassium: 21, phosphorus: 13, energy: 64, tags: ["lps"], sourcePage: 145 },
  { name: "葡萄干", category: "低蛋白淀粉", portion: "20g", protein: 0, sodium: 4, potassium: 182, phosphorus: 17, energy: 63, tags: ["lps", "highK"], sourcePage: 145 },
  { name: "黄豆酱油", category: "调味品", portion: "4g", protein: 0, sodium: 200, potassium: 14, phosphorus: 3, energy: 1, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "老抽", category: "调味品", portion: "3g", protein: 0, sodium: 200, potassium: 13, phosphorus: 5, energy: 4, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "生抽", category: "调味品", portion: "3g", protein: 0, sodium: 200, potassium: 11, phosphorus: 2, energy: 1, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "海鲜酱", category: "调味品", portion: "9g", protein: 0, sodium: 200, potassium: 29, phosphorus: 11, energy: 47, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "牛肉酱", category: "调味品", portion: "16g", protein: 0, sodium: 200, potassium: 31, phosphorus: 7, energy: 77, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "番茄沙司", category: "调味品", portion: "19g", protein: 0, sodium: 200, potassium: 62, phosphorus: 3, energy: 21, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "鸡精", category: "调味品", portion: "1g", protein: 0, sodium: 200, potassium: 1, phosphorus: 1, energy: 9, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "料酒", category: "调味品", portion: "74g", protein: 0, sodium: 200, potassium: 0, phosphorus: 0, energy: 1, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "味精", category: "调味品", portion: "1g", protein: 0, sodium: 200, potassium: 0, phosphorus: 0, energy: 3, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "盐", category: "调味品", portion: "0.5g", protein: 0, sodium: 200, potassium: 0, phosphorus: 0, energy: 0, tags: ["condiment", "highNa"], sourcePage: 146 },
  { name: "均值乳制品", category: "乳制品", portion: "120ml", protein: 4, sodium: 64, potassium: 135, phosphorus: 119, energy: 75, tags: ["dairy"], sourcePage: 123 },
  { name: "鲜赤贝", category: "水产", portion: "50g", protein: 7, sodium: 133, potassium: 77, phosphorus: 59, energy: 31, tags: ["protein", "fish"], sourcePage: 127 },
  { name: "小黄鱼", category: "水产", portion: "40g", protein: 7, sodium: 41, potassium: 91, phosphorus: 75, energy: 40, tags: ["protein", "fish"], sourcePage: 127 },
  { name: "鲈鱼", category: "水产", portion: "30g", protein: 6, sodium: 39, potassium: 96, phosphorus: 70, energy: 26, tags: ["protein", "fish"], sourcePage: 127 },
  { name: "胖头鱼", category: "水产", portion: "45g", protein: 7, sodium: 27, potassium: 103, phosphorus: 81, energy: 45, tags: ["protein", "fish"], sourcePage: 127 },
  { name: "水浸鱿鱼", category: "水产", portion: "35g", protein: 6, sodium: 47, potassium: 6, phosphorus: 21, energy: 26, tags: ["protein", "fish", "lowK"], sourcePage: 127 },
  { name: "鱼片干", category: "水产", portion: "15g", protein: 7, sodium: 348, potassium: 38, phosphorus: 46, energy: 45, tags: ["protein", "fish", "highNa"], sourcePage: 127 },
  { name: "鲴鱼", category: "水产", portion: "35g", protein: 7, sodium: 39, potassium: 241, phosphorus: 130, energy: 35, tags: ["protein", "fish", "highK", "highP"], sourcePage: 127 },
  { name: "鸡肫", category: "家禽类", portion: "40g", protein: 7, sodium: 20, potassium: 82, phosphorus: 65, energy: 78, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸡翅", category: "家禽类", portion: "40g", protein: 7, sodium: 20, potassium: 82, phosphorus: 65, energy: 78, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸡爪", category: "家禽类", portion: "30g", protein: 7, sodium: 51, potassium: 32, phosphorus: 22, energy: 74, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸡肝", category: "家禽类", portion: "40g", protein: 7, sodium: 343, potassium: 87, phosphorus: 52, energy: 99, tags: ["protein", "poultry", "highNa"], sourcePage: 129 },
  { name: "烤鸡", category: "家禽类", portion: "30g", protein: 7, sodium: 142, potassium: 44, phosphorus: 43, energy: 75, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "土鸡", category: "家禽类", portion: "30g", protein: 6, sodium: 22, potassium: 89, phosphorus: 46, energy: 40, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "乌骨鸡", category: "家禽类", portion: "30g", protein: 7, sodium: 19, potassium: 101, phosphorus: 66, energy: 35, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "鸭", category: "家禽类", portion: "45g", protein: 7, sodium: 31, potassium: 86, phosphorus: 55, energy: 108, tags: ["protein", "poultry"], sourcePage: 129 },
  { name: "野兔肉", category: "家禽类", portion: "40g", protein: 7, sodium: 35, potassium: 156, phosphorus: 123, energy: 35, tags: ["protein", "poultry", "highP"], sourcePage: 129 },
  { name: "黑米", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 51, phosphorus: 71, energy: 67, tags: ["grain"], sourcePage: 130 },
  { name: "苦荞麦粉", category: "谷类主食", portion: "25g", protein: 2, sodium: 1, potassium: 80, phosphorus: 61, energy: 76, tags: ["grain"], sourcePage: 130 },
  { name: "面粉", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 26, phosphorus: 23, energy: 70, tags: ["grain"], sourcePage: 130 },
  { name: "年糕", category: "谷类主食", portion: "40g", protein: 1, sodium: 23, potassium: 32, phosphorus: 21, energy: 62, tags: ["grain"], sourcePage: 130 },
  { name: "燕麦片", category: "谷类主食", portion: "25g", protein: 4, sodium: 1, potassium: 54, phosphorus: 73, energy: 92, tags: ["grain"], sourcePage: 130 },
  { name: "薏米", category: "谷类主食", portion: "20g", protein: 3, sodium: 1, potassium: 48, phosphorus: 43, energy: 71, tags: ["grain"], sourcePage: 130 },
  { name: "玉米(干)", category: "谷类主食", portion: "20g", protein: 2, sodium: 1, potassium: 60, phosphorus: 44, energy: 67, tags: ["grain"], sourcePage: 131 },
  { name: "玉米(鲜)", category: "谷类主食", portion: "75g", protein: 3, sodium: 1, potassium: 179, phosphorus: 88, energy: 80, tags: ["grain"], sourcePage: 131 },
  { name: "菜肉馄饨", category: "谷类主食", portion: "50g", protein: 3, sodium: 18, potassium: 51, phosphorus: 43, energy: 113, tags: ["grain"], sourcePage: 131 },
  { name: "菜肉水饺", category: "谷类主食", portion: "45g", protein: 3, sodium: 11, potassium: 59, phosphorus: 52, energy: 96, tags: ["grain"], sourcePage: 131 },
  { name: "叉烧包", category: "谷类主食", portion: "35g", protein: 3, sodium: 93, potassium: 70, phosphorus: 40, energy: 85, tags: ["grain"], sourcePage: 131 },
  { name: "春卷", category: "谷类主食", portion: "40g", protein: 2, sodium: 194, potassium: 36, phosphorus: 38, energy: 185, tags: ["grain", "highNa"], sourcePage: 131 },
  { name: "豆沙汤团", category: "谷类主食", portion: "30g", protein: 1, sodium: 0, potassium: 33, phosphorus: 18, energy: 61, tags: ["grain"], sourcePage: 131 },
  { name: "烧卖", category: "谷类主食", portion: "45g", protein: 2, sodium: 61, potassium: 27, phosphorus: 19, energy: 115, tags: ["grain"], sourcePage: 131 },
  { name: "生煎", category: "谷类主食", portion: "40g", protein: 3, sodium: 136, potassium: 43, phosphorus: 36, energy: 93, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉大包", category: "谷类主食", portion: "40g", protein: 3, sodium: 185, potassium: 46, phosphorus: 36, energy: 94, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉锅贴", category: "谷类主食", portion: "45g", protein: 4, sodium: 2, potassium: 59, phosphorus: 50, energy: 113, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉水饺", category: "谷类主食", portion: "60g", protein: 4, sodium: 15, potassium: 74, phosphorus: 51, energy: 131, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉汤团", category: "谷类主食", portion: "40g", protein: 2, sodium: 68, potassium: 33, phosphorus: 29, energy: 92, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉粽", category: "谷类主食", portion: "30g", protein: 2, sodium: 31, potassium: 55, phosphorus: 30, energy: 70, tags: ["grain"], sourcePage: 131 },
  { name: "鲜肉月饼", category: "谷类主食", portion: "30g", protein: 3, sodium: 5, potassium: 57, phosphorus: 41, energy: 127, tags: ["grain"], sourcePage: 131 },
  { name: "香菇菜包", category: "谷类主食", portion: "40g", protein: 3, sodium: 189, potassium: 37, phosphorus: 31, energy: 72, tags: ["grain"], sourcePage: 131 },
  { name: "小笼馒头", category: "谷类主食", portion: "45g", protein: 4, sodium: 339, potassium: 62, phosphorus: 45, energy: 112, tags: ["grain", "highNa"], sourcePage: 131 },
  { name: "花卷", category: "谷类主食", portion: "30g", protein: 2, sodium: 29, potassium: 25, phosphorus: 22, energy: 65, tags: ["grain"], sourcePage: 132 },
  { name: "馒头", category: "谷类主食", portion: "20g", protein: 2, sodium: 0, potassium: 37, phosphorus: 36, energy: 68, tags: ["grain"], sourcePage: 132 },
  { name: "切片面包", category: "谷类主食", portion: "30g", protein: 2, sodium: 1, potassium: 20, phosphorus: 19, energy: 79, tags: ["grain"], sourcePage: 132 },
  { name: "小餐包", category: "谷类主食", portion: "30g", protein: 2, sodium: 1, potassium: 20, phosphorus: 19, energy: 79, tags: ["grain"], sourcePage: 132 },
  { name: "煮面条", category: "谷类主食", portion: "60g", protein: 2, sodium: 16, potassium: 9, phosphorus: 15, energy: 65, tags: ["grain"], sourcePage: 132 },
  { name: "谷类均值", category: "谷类主食", portion: "1份", protein: 2, sodium: 87, potassium: 44, phosphorus: 33, energy: 92, tags: ["grain"], sourcePage: 132 },
  { name: "马齿苋", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 0, potassium: 0, phosphorus: 28, energy: 14, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "牛蒡叶", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 15, energy: 9, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "野韭菜", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 12, energy: 9, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "野芜菜", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 23, energy: 15, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "菌陈蒿", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 0, potassium: 0, phosphorus: 24, energy: 14, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "草头", category: "蔬菜-低钾", portion: "25g", protein: 1, sodium: 7, potassium: 8, phosphorus: 6, energy: 8, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "发菜(干)", category: "蔬菜-低钾", portion: "5g", protein: 1, sodium: 5, potassium: 11, phosphorus: 4, energy: 9, tags: ["vegetable", "lowK"], sourcePage: 133 },
  { name: "木耳(水发)", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 4, potassium: 26, phosphorus: 6, energy: 11, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "山药(干)", category: "蔬菜-低钾", portion: "10g", protein: 1, sodium: 10, potassium: 27, phosphorus: 2, energy: 32, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "金针菜", category: "蔬菜-低钾", portion: "5g", protein: 1, sodium: 3, potassium: 31, phosphorus: 11, energy: 10, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "甘薯", category: "蔬菜-低钾", portion: "25g", protein: 0, sodium: 7, potassium: 33, phosphorus: 10, energy: 25, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "花菜", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 12, potassium: 35, phosphorus: 20, energy: 12, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "洋葱", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 2, potassium: 37, phosphorus: 17, energy: 23, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "韭菜", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 3, potassium: 38, phosphorus: 19, energy: 11, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "冬菇(干)", category: "蔬菜-低钾", portion: "5g", protein: 1, sodium: 1, potassium: 58, phosphorus: 23, energy: 11, tags: ["vegetable", "lowK"], sourcePage: 134 },
  { name: "黄瓜", category: "蔬菜-低钾", portion: "150g", protein: 1, sodium: 21, potassium: 89, phosphorus: 33, energy: 17, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "草菇", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 37, potassium: 90, phosphorus: 17, energy: 12, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "豆瓣菜", category: "蔬菜-低钾", portion: "50g", protein: 1, sodium: 31, potassium: 90, phosphorus: 13, energy: 9, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "蒜头", category: "蔬菜-低钾", portion: "20g", protein: 1, sodium: 2, potassium: 92, phosphorus: 42, energy: 26, tags: ["vegetable", "lowK"], sourcePage: 135 },
  { name: "油菜", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 28, potassium: 105, phosphorus: 20, energy: 12, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "空心菜", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 99, potassium: 107, phosphorus: 24, energy: 11, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "毛笋", category: "蔬菜-中钾", portion: "50g", protein: 2, sodium: 0, potassium: 110, phosphorus: 19, energy: 10, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "芥菜头", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 33, potassium: 122, phosphorus: 18, energy: 17, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "荸荠", category: "蔬菜-中钾", portion: "40g", protein: 0, sodium: 6, potassium: 122, phosphorus: 18, energy: 24, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "黄苔叶", category: "蔬菜-中钾", portion: "75g", protein: 1, sodium: 27, potassium: 124, phosphorus: 22, energy: 14, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "水发黄蘑", category: "蔬菜-中钾", portion: "25g", protein: 1, sodium: 0, potassium: 128, phosphorus: 13, energy: 5, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "雪里蕻", category: "蔬菜-中钾", portion: "50g", protein: 1, sodium: 15, potassium: 141, phosphorus: 24, energy: 12, tags: ["vegetable", "moderateK"], sourcePage: 136 },
  { name: "冬瓜", category: "蔬菜-高钾", portion: "200g", protein: 1, sodium: 2, potassium: 228, phosphorus: 24, energy: 18, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "甜菜叶", category: "蔬菜-高钾", portion: "50g", protein: 1, sodium: 101, potassium: 274, phosphorus: 20, energy: 10, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "菊苣", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 22, potassium: 314, phosphorus: 28, energy: 17, tags: ["vegetable", "highK"], sourcePage: 137 },
  { name: "长萝卜", category: "蔬菜-高钾", portion: "100g", protein: 1, sodium: 63, potassium: 449, phosphorus: 17, energy: 17, tags: ["vegetable", "veryHighK"], sourcePage: 138 },
  { name: "杏仁露", category: "水果-低钾", portion: "185g", protein: 2, sodium: 17, potassium: 2, phosphorus: 2, energy: 85, tags: ["fruit", "lowK"], sourcePage: 139 },
  { name: "无核黑枣", category: "水果-低钾", portion: "25g", protein: 0, sodium: 2, potassium: 120, phosphorus: 16, energy: 57, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "柿", category: "水果-低钾", portion: "80g", protein: 0, sodium: 1, potassium: 121, phosphorus: 18, energy: 57, tags: ["fruit", "lowK"], sourcePage: 140 },
  { name: "菠萝", category: "水果-中钾", portion: "150g", protein: 1, sodium: 1, potassium: 170, phosphorus: 14, energy: 62, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "红富士苹果", category: "水果-中钾", portion: "150g", protein: 1, sodium: 1, potassium: 173, phosphorus: 17, energy: 68, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "金橘", category: "水果-中钾", portion: "120g", protein: 1, sodium: 4, potassium: 173, phosphorus: 24, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "猕猴桃", category: "水果-中钾", portion: "120g", protein: 1, sodium: 12, potassium: 173, phosphorus: 31, energy: 67, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "香蕉", category: "水果-中钾", portion: "70g", protein: 1, sodium: 1, potassium: 179, phosphorus: 20, energy: 64, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "鲜枣", category: "水果-中钾", portion: "50g", protein: 1, sodium: 1, potassium: 188, phosphorus: 12, energy: 61, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "柚", category: "水果-中钾", portion: "160g", protein: 1, sodium: 5, potassium: 190, phosphorus: 38, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "山楂", category: "水果-中钾", portion: "65g", protein: 0, sodium: 4, potassium: 194, phosphorus: 16, energy: 62, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "柑", category: "水果-中钾", portion: "130g", protein: 1, sodium: 2, potassium: 200, phosphorus: 23, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "橙汁", category: "水果-中钾", portion: "135g", protein: 1, sodium: 4, potassium: 203, phosphorus: 18, energy: 62, tags: ["fruit", "moderateK", "juice"], sourcePage: 140 },
  { name: "枇杷", category: "水果-中钾", portion: "170g", protein: 1, sodium: 7, potassium: 207, phosphorus: 14, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "石榴", category: "水果-中钾", portion: "100g", protein: 1, sodium: 1, potassium: 218, phosphorus: 76, energy: 64, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "橙", category: "水果-中钾", portion: "140g", protein: 1, sodium: 2, potassium: 223, phosphorus: 31, energy: 66, tags: ["fruit", "moderateK"], sourcePage: 140 },
  { name: "紫葡萄", category: "水果-中钾", portion: "150g", protein: 1, sodium: 3, potassium: 227, phosphorus: 15, energy: 65, tags: ["fruit", "moderateK"], sourcePage: 141 },
  { name: "椰子", category: "水果-中钾", portion: "50g", protein: 2, sodium: 28, potassium: 238, phosphorus: 45, energy: 116, tags: ["fruit", "moderateK"], sourcePage: 141 },
];

window.FOOD_EXCHANGE_REFERENCE = [
  {
    title: "谷薯豆类交换份",
    summary: "每份约 90 kcal，可按主食类型互换。",
    sourcePage: 20,
    rows: [
      "谷物 25g，蛋白 2.5g，脂肪 0.5g，碳水 19.0g",
      "面制品 35g，蛋白 2.5g，脂肪 0.4g，碳水 18.0g",
      "米饭 75g，蛋白 2.0g，脂肪 0.2g，碳水 19.4g",
      "全谷物 25g，蛋白 2.5g，脂肪 0.7g，碳水 18.0g",
      "杂豆类 25g，蛋白 5.5g，脂肪 0.5g，碳水 15.0g",
      "粉条/淀粉类 25g，蛋白 0.3g，脂肪 0g，碳水 21.2g",
      "薯芋类 100g，蛋白 1.9g，脂肪 0.2g，碳水 20.0g",
    ],
  },
  {
    title: "蔬菜类交换份",
    summary: "每份约 90 kcal，深浅色和类别可互换。",
    sourcePage: 21,
    rows: [
      "蔬菜综合 250g，蛋白 4.5g，脂肪 0.7g，碳水 16.0g",
      "嫩茎花花菜类 深色 300g / 浅色 330g",
      "茄果类 375g，蛋白 3.8g，脂肪 0.7g，碳水 18.0g",
      "根茎类 300g，蛋白 3.2g，脂肪 0.5g，碳水 19.2g",
      "菌菇类 鲜 275g / 干 30g",
      "鲜豆类 250g，蛋白 6.3g，脂肪 0.7g，碳水 15.4g",
    ],
  },
  {
    title: "水果类交换份",
    summary: "每份约 90 kcal，可在同类水果间互换。",
    sourcePage: 22,
    rows: [
      "水果综合 150g，蛋白 1.0g，脂肪 0.6g，碳水 20.0g",
      "柑橘类 200g，蛋白 1.7g，脂肪 0.6g，碳水 20.0g",
      "仁果/核果/瓜果类 175g，蛋白 0.8g，脂肪 0.4g，碳水 21.0g",
      "浆果类 150g，蛋白 1.4g，脂肪 0.5g，碳水 20.0g",
      "枣和热带水果类 75g，蛋白 1.1g，脂肪 1.1g，碳水 18.0g",
      "果干类 25g，蛋白 0.7g，脂肪 0.3g，碳水 19.0g",
    ],
  },
  {
    title: "肉蛋水产品交换份",
    summary: "每份约 90 kcal，优先选择低脂高优质蛋白来源。",
    sourcePage: 23,
    rows: [
      "畜肉综合 50g，蛋白 8.0g，脂肪 6.7g",
      "畜肉脂肪 ≤5% 80g，蛋白 16.0g，脂肪 2.1g",
      "禽肉类 50g，蛋白 8.8g，脂肪 6.0g",
      "蛋类 60g，蛋白 7.6g，脂肪 6.6g",
      "水产综合 90g，蛋白 14.8g，脂肪 2.9g",
      "鱼类 75g，蛋白 13.7g，脂肪 3.2g",
      "虾蟹贝类 115g，蛋白 15.8g，脂肪 1.5g",
    ],
  },
  {
    title: "坚果与豆乳制品交换份",
    summary: "坚果、豆类和乳制品同样按 90 kcal 计算交换。",
    sourcePage: 24,
    rows: [
      "坚果综合 20g，蛋白 3.2g，脂肪 5.8g，碳水 6.5g",
      "高脂坚果 15g，中脂坚果 20g，淀粉坚果 25g",
      "大豆类 20g，蛋白 6.9g，脂肪 3.3g，碳水 7.0g",
      "豆浆 330g，蛋白 8.0g，脂肪 3.1g，碳水 8.0g",
      "北豆腐 90g / 南豆腐 150g",
      "全脂奶 150g / 脱脂乳 265g / 乳酪 25g",
    ],
  },
  {
    title: "调味料钠交换",
    summary: "以 400mg 钠为 1 份，便于估算限盐。",
    sourcePage: 25,
    rows: [
      "食用盐 1g ≈ 钠 400mg",
      "鸡精 2g ≈ 钠 400mg",
      "味精 4.8g ≈ 钠 400mg",
      "豆瓣酱等 6g ≈ 钠 400mg",
      "酱油 6.5g ≈ 钠 400mg",
      "咸菜 13g / 腐乳 17g ≈ 钠 400mg",
    ],
  },
];

window.NUTRITION_LABEL_GUIDANCE = [
  {
    title: "读营养标签先看四项",
    sourcePage: 15,
    items: [
      "蛋白质用于核算全天总量，避免不知不觉超标。",
      "钠含量决定“咸不咸”，加工食品优先比较每 100g 钠值。",
      "血钾或血磷异常时，优先查看钾、磷含量而不是只看热量。",
      "同类产品尽量统一按每 100g 或每份比较，避免被包装规格误导。",
    ],
  },
  {
    title: "控磷时可看磷/蛋白比",
    sourcePage: 16,
    items: [
      "磷/蛋白比 <10 mg/g，通常更适合未透析 CKD 日常选择。",
      "10-15 mg/g 需结合总量控制，频次不宜过高。",
      "15-20 mg/g 为高磷密度食物，异常期应明显减少。",
      ">20 mg/g 多见于部分加工海产、动物内脏或高磷添加食品，应谨慎。",
    ],
  },
  {
    title: "加工调味料要做钠换算",
    sourcePage: 25,
    items: [
      "食盐 1g 约等于钠 400mg，可用于快速换算每日盐量。",
      "酱油、鸡精、豆瓣酱、咸菜都应计入总钠，而不是只算额外放盐。",
      "高血压、水肿或少尿时，先减调味料往往比单纯少吃主食更有效。",
    ],
  },
];

window.GUIDELINE_RECIPES = {
  breakfast: [
    {
      id: "gb1",
      title: "山药丝饼 + 牛奶",
      subtitle: "参考指南东北秋季 1-2 期食谱，早餐更偏温和易执行。",
      ingredients: ["鲜山药 200g", "小麦淀粉 40g", "牛奶 250mL", "西芹 50g", "腐竹 5g"],
      nutrients: { energy: 295, protein: 11, sodium: 165, potassium: 265, phosphorus: 125 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 28 页，东北地区秋季 1-2 期早餐示例。",
    },
    {
      id: "gb2",
      title: "油饼 + 腐竹瓜片 + 大枣粥",
      subtitle: "参考指南东北春季 3-5 期食谱，兼顾主食和低蛋白主食搭配。",
      ingredients: ["面粉 55g", "小麦淀粉 10g", "黄瓜 100g", "腐竹 25g", "低蛋白大米 25g", "大枣 5g"],
      nutrients: { energy: 338, protein: 8, sodium: 152, potassium: 188, phosphorus: 92 },
      flags: ["stage45", "lowP"],
      sourceNote: "指南附录 3，第 28 页，东北地区春季 3-5 期早餐示例。",
    },
    {
      id: "gb3",
      title: "玉米面花卷 + 鸡蛋羹",
      subtitle: "参考指南西北秋季 1-2 期食谱，主食和优质蛋白更容易落地。",
      ingredients: ["玉米面 50g", "鸡蛋 30g", "芦笋 100g", "牛奶 150mL"],
      nutrients: { energy: 286, protein: 10, sodium: 148, potassium: 205, phosphorus: 118 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 33 页，西北地区秋季 1-2 期早餐示例。",
    },
    {
      id: "gb4",
      title: "豆浆 + 烤饼 + 煎鸡蛋",
      subtitle: "参考指南华北春季 1-2 期食谱，面食型早餐更贴近日常习惯。",
      ingredients: ["豆浆 200mL", "面粉 30g", "鸡蛋 50g", "黄瓜 50g"],
      nutrients: { energy: 298, protein: 13, sodium: 182, potassium: 218, phosphorus: 126 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 40 页，华北地区春季 1-2 期早餐示例。",
    },
    {
      id: "gb5",
      title: "桃花饼 + 牛奶",
      subtitle: "参考指南华东春季 1-2 期食谱，早餐口味更清爽。",
      ingredients: ["鲜桃花 100g", "小麦淀粉 80g", "牛奶 250mL"],
      nutrients: { energy: 304, protein: 9, sodium: 148, potassium: 185, phosphorus: 110 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 45 页，华东地区春季 1-2 期早餐示例。",
    },
    {
      id: "gb6",
      title: "青菜香菇包 + 牛奶",
      subtitle: "参考指南华中春季 1-2 期食谱，兼顾主食和乳制品补能量。",
      ingredients: ["面粉 120g", "香菇 20g", "小白菜 20g", "牛奶 250mL"],
      nutrients: { energy: 318, protein: 11, sodium: 176, potassium: 214, phosphorus: 122 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 50 页，华中地区春季 1-2 期早餐示例。",
    },
    {
      id: "gb7",
      title: "肥肠粉 + 鸡蛋羹",
      subtitle: "参考指南西南春季 1-2 期食谱，更接近西南地区早餐结构。",
      ingredients: ["米粉 100g", "红薯粉 75g", "肥肠 25g", "鸡蛋 25g"],
      nutrients: { energy: 342, protein: 12, sodium: 236, potassium: 268, phosphorus: 132 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 55 页，西南地区春季 1-2 期早餐示例。",
    },
    {
      id: "gb8",
      title: "鸡蛋虾仁蒸粉丝",
      subtitle: "参考指南华南春季 1-2 期食谱，符合华南偏清淡的早餐习惯。",
      ingredients: ["鲜虾 75g", "豌豆粉丝 75g", "鸡蛋 60g"],
      nutrients: { energy: 312, protein: 17, sodium: 244, potassium: 242, phosphorus: 158 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 60 页，华南地区春季 1-2 期早餐示例。",
    },
    {
      id: "gb9",
      title: "山药肉末粥 + 凉拌海带丝",
      subtitle: "参考指南华南春季 3-5 期食谱，用低蛋白阶段早餐思路替代高蛋白早餐。",
      ingredients: ["鲜山药 75g", "小米 25g", "猪瘦肉 15g", "海带 75g"],
      nutrients: { energy: 258, protein: 8, sodium: 168, potassium: 198, phosphorus: 92 },
      flags: ["stage45", "lowP"],
      sourceNote: "指南附录 3，第 61 页，华南地区春季 3-5 期早餐示例。",
    },
  ],
  lunch: [
    {
      id: "gl1",
      title: "白菜猪肉粉条炖豆腐 + 油泼麦菜",
      subtitle: "参考指南东北秋季 1-2 期食谱，主菜加蔬菜的午餐组合。",
      ingredients: ["大白菜 100g", "豆腐 60g", "粉条 25g", "猪五花肉 20g", "油麦菜 100g", "低蛋白大米 50g"],
      nutrients: { energy: 438, protein: 14, sodium: 385, potassium: 295, phosphorus: 152 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 28 页，东北地区秋季 1-2 期午餐示例。",
    },
    {
      id: "gl2",
      title: "西红柿炒鸡蛋 + 尖椒茄子丝",
      subtitle: "参考指南东北春季 3-5 期食谱，更贴近当前低蛋白阶段逻辑。",
      ingredients: ["西红柿 100g", "鸡蛋 50g", "茄子 100g", "尖椒 30g", "低蛋白大米 100g"],
      nutrients: { energy: 405, protein: 10, sodium: 218, potassium: 258, phosphorus: 116 },
      flags: ["stage45", "lowP"],
      sourceNote: "指南附录 3，第 28 页，东北地区春季 3-5 期午餐示例。",
    },
    {
      id: "gl3",
      title: "清蒸山药大虾 + 海米冬瓜汤",
      subtitle: "参考指南西北夏季 1-2 期食谱，午餐结构更清爽。",
      ingredients: ["鲜山药 150g", "大虾 50g", "冬瓜 150g", "海米 5g", "低蛋白玉米水饺 50g"],
      nutrients: { energy: 422, protein: 15, sodium: 326, potassium: 305, phosphorus: 148 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 32-33 页，西北地区夏季 1-2 期午餐示例。",
    },
    {
      id: "gl4",
      title: "低蛋白大米饭 + 鲅鱼北豆腐",
      subtitle: "参考指南华北春季 3-5 期食谱，突出低蛋白主食与豆鱼搭配。",
      ingredients: ["低蛋白大米 50g", "鲅鱼 80g", "北豆腐 100g", "芹菜 150g"],
      nutrients: { energy: 398, protein: 11, sodium: 228, potassium: 256, phosphorus: 126 },
      flags: ["stage45", "lowP"],
      sourceNote: "指南附录 3，第 41 页，华北地区春季 3-5 期午餐示例。",
    },
    {
      id: "gl5",
      title: "低蛋白大米饭 + 龙井虾仁",
      subtitle: "参考指南华东春季 1-2 期食谱，偏清鲜口味。",
      ingredients: ["低蛋白大米 90g", "虾仁 70g", "蛋清 20g", "龙井 3g", "蒜泥米苋 150g"],
      nutrients: { energy: 428, protein: 16, sodium: 214, potassium: 286, phosphorus: 152 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 45 页，华东地区春季 1-2 期午餐示例。",
    },
    {
      id: "gl6",
      title: "大米饭 + 青椒萝卜丝 + 豆腐汤",
      subtitle: "参考指南华中春季 1-2 期食谱，结构朴素但长期可执行。",
      ingredients: ["大米 80g", "青椒 100g", "白萝卜 100g", "西红柿 80g", "南豆腐 50g"],
      nutrients: { energy: 396, protein: 11, sodium: 198, potassium: 292, phosphorus: 118 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 50 页，华中地区春季 1-2 期午餐示例。",
    },
    {
      id: "gl7",
      title: "米饭 + 玫瑰盐煎肉 + 蒜蓉生菜",
      subtitle: "参考指南西南春季 1-2 期食谱，保留地区风味但控制总量。",
      ingredients: ["大米 50g", "猪瘦肉 60g", "红薯淀粉 50g", "生菜 150g"],
      nutrients: { energy: 418, protein: 15, sodium: 248, potassium: 304, phosphorus: 144 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 55 页，西南地区春季 1-2 期午餐示例。",
    },
    {
      id: "gl8",
      title: "米饭 + 香菇鸡 + 蒜炒苋菜",
      subtitle: "参考指南华南春季 1-2 期食谱，符合华南家常正餐搭配。",
      ingredients: ["大米 75g", "鸡肉 50g", "香菇干 10g", "苋菜 150g"],
      nutrients: { energy: 408, protein: 15, sodium: 206, potassium: 288, phosphorus: 142 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 60 页，华南地区春季 1-2 期午餐示例。",
    },
    {
      id: "gl9",
      title: "米饭 + 春笋芥蓝 + 蒜炒油麦菜",
      subtitle: "参考指南华南春季 3-5 期食谱，更适合当前低蛋白阶段。",
      ingredients: ["大米 60g", "猪小排 50g", "芋头 50g", "春笋 100g", "油麦菜 200g"],
      nutrients: { energy: 372, protein: 10, sodium: 214, potassium: 248, phosphorus: 108 },
      flags: ["stage45", "lowP"],
      sourceNote: "指南附录 3，第 62 页，华南地区春季 3-5 期午餐示例。",
    },
  ],
  dinner: [
    {
      id: "gd1",
      title: "红薯发糕 + 牛肉炒蒜苔",
      subtitle: "参考指南西北春季 1-2 期食谱，主食和肉菜搭配较完整。",
      ingredients: ["红薯 100g", "面粉 60g", "蒜苔 100g", "牛肉 25g", "素炒南瓜片 150g"],
      nutrients: { energy: 418, protein: 15, sodium: 235, potassium: 318, phosphorus: 160 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 32 页，西北地区春季 1-2 期晚餐示例。",
    },
    {
      id: "gd2",
      title: "肉丝白菜炖粉条 + 低蛋白大米饭",
      subtitle: "参考指南东北秋季 3-5 期食谱，适合当前低蛋白阶段参考。",
      ingredients: ["小白菜 100g", "粉条 40g", "猪瘦肉 10g", "低蛋白大米 50g", "蒜蓉炒丝瓜 125g"],
      nutrients: { energy: 372, protein: 9, sodium: 205, potassium: 228, phosphorus: 102 },
      flags: ["stage45", "lowP", "lowK"],
      sourceNote: "指南附录 3，第 29 页，东北地区秋季 3-5 期晚餐示例。",
    },
    {
      id: "gd3",
      title: "西红柿炒鸡蛋 + 冬瓜粉丝汤",
      subtitle: "参考指南西北秋季 1-2 期食谱，清淡晚餐更易长期坚持。",
      ingredients: ["西红柿 100g", "鸡蛋 30g", "粉丝 20g", "冬瓜 75g", "麻团炒芹菜 100g"],
      nutrients: { energy: 358, protein: 10, sodium: 198, potassium: 242, phosphorus: 112 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 33 页，西北地区秋季 1-2 期晚餐示例。",
    },
    {
      id: "gd4",
      title: "香椿炒蛋 + 清炒上海青",
      subtitle: "参考指南华东春季 1-2 期食谱，晚餐更偏清鲜家常。",
      ingredients: ["香椿 100g", "鸡蛋 70g", "低蛋白大米 90g", "上海青 150g"],
      nutrients: { energy: 364, protein: 12, sodium: 188, potassium: 246, phosphorus: 128 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 45 页，华东地区春季 1-2 期晚餐示例。",
    },
    {
      id: "gd5",
      title: "山药大米饭 + 彩椒百花 + 白菜肉丸",
      subtitle: "参考指南华中春季 3-5 期食谱，晚餐控制蛋白同时保留风味。",
      ingredients: ["鲜山药 50g", "大米 50g", "西兰花 150g", "柿子椒 10g", "大白菜 100g", "鸡胸肉 20g"],
      nutrients: { energy: 352, protein: 9, sodium: 196, potassium: 236, phosphorus: 98 },
      flags: ["stage45", "lowP"],
      sourceNote: "指南附录 3，第 51 页，华中地区春季 3-5 期晚餐示例。",
    },
    {
      id: "gd6",
      title: "低蛋白大米饭 + 虎皮青椒",
      subtitle: "参考指南西南春季 3-5 期食谱，以家常蔬菜为主降低蛋白负担。",
      ingredients: ["低蛋白大米 80g", "青椒 100g", "冬笋 100g", "茄子 50g"],
      nutrients: { energy: 338, protein: 7.8, sodium: 168, potassium: 210, phosphorus: 82 },
      flags: ["stage45", "lowP", "lowK"],
      sourceNote: "指南附录 3，第 56-57 页，西南地区春季 3-5 期晚餐示例。",
    },
    {
      id: "gd7",
      title: "米饭 + 南瓜蒸排骨 + 鲍大豆芽",
      subtitle: "参考指南华南春季 1-2 期食谱，保留华南蒸菜习惯。",
      ingredients: ["大米 75g", "南瓜 75g", "猪小排 75g", "黄豆芽 100g"],
      nutrients: { energy: 404, protein: 16, sodium: 214, potassium: 296, phosphorus: 154 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 60 页，华南地区春季 1-2 期晚餐示例。",
    },
    {
      id: "gd8",
      title: "西红柿鸡蛋炒馓针",
      subtitle: "参考指南华南春季 3-5 期食谱，用麦淀粉类主食完成低蛋白晚餐。",
      ingredients: ["西红柿 250g", "小麦淀粉 100g", "鸡蛋 50g"],
      nutrients: { energy: 348, protein: 8.6, sodium: 172, potassium: 228, phosphorus: 88 },
      flags: ["stage45", "lowP"],
      sourceNote: "指南附录 3，第 62 页，华南地区春季 3-5 期晚餐示例。",
    },
  ],
  snack: [
    {
      id: "gs1",
      title: "草莓 200g",
      subtitle: "指南附录中的常见加餐示例，适合常规日补充能量。",
      ingredients: ["草莓 200g"],
      nutrients: { energy: 68, protein: 1, sodium: 1, potassium: 227, phosphorus: 19 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 27-29 页，多组食谱中的加餐示例。",
    },
    {
      id: "gs2",
      title: "苹果 + 榛子仁",
      subtitle: "参考指南东北春季 3-5 期食谱，加餐以水果为主并少量补能量。",
      ingredients: ["苹果 100g", "榛子仁 10g"],
      nutrients: { energy: 112, protein: 1.8, sodium: 2, potassium: 118, phosphorus: 28 },
      flags: ["stage45", "lowP"],
      sourceNote: "指南附录 3，第 28 页，东北地区春季 3-5 期加餐示例。",
    },
    {
      id: "gs3",
      title: "酸奶 200g",
      subtitle: "参考指南西北夏季 1-2 期食谱，适合食欲一般时加餐。",
      ingredients: ["酸奶 200g"],
      nutrients: { energy: 120, protein: 6, sodium: 80, potassium: 230, phosphorus: 140 },
      flags: ["default"],
      sourceNote: "指南附录 3，第 33 页，西北地区夏季 1-2 期加餐示例。",
    },
    {
      id: "gs4",
      title: "柚子 100g",
      subtitle: "参考指南华北春季 1-2 期食谱，适合常规日水果加餐。",
      ingredients: ["柚子 100g"],
      nutrients: { energy: 41, protein: 0.6, sodium: 3, potassium: 119, phosphorus: 24 },
      flags: ["default", "lowP"],
      sourceNote: "指南附录 3，第 39-40 页，华北地区春季 1-2 期加餐示例。",
    },
    {
      id: "gs5",
      title: "甘蔗 100g",
      subtitle: "参考指南华中春季 3-5 期食谱，用于低蛋白阶段小份加餐。",
      ingredients: ["甘蔗 100g"],
      nutrients: { energy: 64, protein: 0.5, sodium: 3, potassium: 110, phosphorus: 6 },
      flags: ["stage45", "lowP"],
      sourceNote: "指南附录 3，第 51 页，华中地区春季 3-5 期加餐示例。",
    },
    {
      id: "gs6",
      title: "橙子 200g",
      subtitle: "参考指南西南春季 3-5 期食谱，水果加餐更接近地区原始示例。",
      ingredients: ["橙子 200g"],
      nutrients: { energy: 94, protein: 1.8, sodium: 4, potassium: 186, phosphorus: 26 },
      flags: ["stage45"],
      sourceNote: "指南附录 3，第 56 页，西南地区春季 3-5 期加餐示例。",
    },
  ],
};

window.GUIDELINE_DAY_PLANS = [
  {
    id: "dp-ne-autumn-12",
    region: "东北地区",
    season: "秋季",
    stageGroup: "1-2",
    title: "东北地区秋季整日方案",
    sourceNote: "指南附录 3，第 28 页，慢性肾脏病 1-2 期秋季食谱。",
    meals: {
      breakfast: "山药丝饼、牛奶、西芹拌腐竹",
      snack1: "甜瓜",
      lunch: "白菜猪肉粉条炖豆腐、清炒油麦菜、杂粮饭",
      snack2: "核桃",
      dinner: "青椒炒蛋、小鸡炖蘑菇、馒头",
    },
    highlights: ["山药、小麦淀粉和低蛋白大米搭配，兼顾能量与蛋白控制", "更贴近东北秋季家常饮食结构"],
    totals: { energy: 1811, protein: 47, fat: 66, carbs: 270, sodium: 1777, potassium: 2054, phosphorus: 808 },
  },
  {
    id: "dp-ne-spring-35",
    region: "东北地区",
    season: "春季",
    stageGroup: "3-5",
    title: "东北地区春季整日方案",
    sourceNote: "指南附录 3，第 28-29 页，慢性肾脏病 3-5 期春季食谱。",
    meals: {
      breakfast: "油饼、腐竹瓜片、大枣粥",
      snack1: "苹果、榛子仁",
      lunch: "西红柿炒鸡蛋、尖椒茄子丝、低蛋白大米饭",
      snack2: "草莓",
      dinner: "家常炖菜、尖椒土片丝、低蛋白大米饭",
    },
    highlights: ["突出低蛋白主食和蔬菜搭配", "适合 3-5 期未透析阶段作一日模板参考"],
    totals: { energy: 1819, protein: 37, fat: 57, carbs: 297, sodium: 1446, potassium: 1541, phosphorus: 594 },
  },
  {
    id: "dp-nw-spring-12",
    region: "西北地区",
    season: "春季",
    stageGroup: "1-2",
    title: "西北地区春季整日方案",
    sourceNote: "指南附录 3，第 32 页，慢性肾脏病 1-2 期春季食谱。",
    meals: {
      breakfast: "全麦馒头、羊奶、鸡蛋羹、炝拌三丝",
      snack1: "柿子",
      lunch: "低蛋白大米饭、西红柿炒菜花、清蒸山药大虾、青菜汤",
      snack2: "猕猴桃",
      dinner: "红薯发糕、牛肉炒蒜苔、素炒葫芦瓜",
    },
    highlights: ["以面食和奶类为主，贴合西北春季日常结构", "蔬菜和主食安排更完整"],
    totals: { energy: 1803, protein: 46, fat: 54, carbs: 291, sodium: 2013, potassium: 2108, phosphorus: 821 },
  },
  {
    id: "dp-nw-autumn-12",
    region: "西北地区",
    season: "秋季",
    stageGroup: "1-2",
    title: "西北地区秋季整日方案",
    sourceNote: "指南附录 3，第 33 页，慢性肾脏病 1-2 期秋季食谱。",
    meals: {
      breakfast: "玉米面花卷、酸奶、鸡蛋卷、清炒西葫芦",
      snack1: "苹果",
      lunch: "蒸玉米、西红柿牛肉末、清炒蒜片",
      snack2: "鲜枣",
      dinner: "杂粮煎饼、莲子百合饭、鸡丝炒花菜",
    },
    highlights: ["秋季以面食和玉米类主食为主", "更适合作为北方家庭的一日样例"],
    totals: { energy: 1845, protein: 50, fat: 51, carbs: 301, sodium: 1845, potassium: 2628, phosphorus: 900 },
  },
  {
    id: "dp-hb-spring-12",
    region: "华北地区",
    season: "春季",
    stageGroup: "1-2",
    title: "华北地区春季整日方案",
    sourceNote: "指南附录 3，第 40 页，慢性肾脏病 1-2 期春季食谱。",
    meals: {
      breakfast: "豆浆、烤饼、煎鸡蛋",
      snack1: "苹果",
      lunch: "低蛋白大米饭、红烧肉炖白菜粉丝、拌菠菜",
      snack2: "苹果或柚子类水果",
      dinner: "蒸饺、黑芝麻拌木耳、青椒洋葱片",
    },
    highlights: ["面食比例较高，符合华北家常结构", "盐和肉量较传统吃法做了压缩"],
    totals: { energy: 1809, protein: 48, fat: 58, carbs: 283, sodium: 1509, potassium: 2177, phosphorus: 735 },
  },
  {
    id: "dp-hd-spring-12",
    region: "华东地区",
    season: "春季",
    stageGroup: "1-2",
    title: "华东地区春季整日方案",
    sourceNote: "指南附录 3，第 45 页，慢性肾脏病 1-2 期春季食谱。",
    meals: {
      breakfast: "桃花饼、牛奶",
      snack1: "芒果",
      lunch: "低蛋白大米饭、龙井虾仁、蒜泥米苋",
      snack2: "木瓜",
      dinner: "低蛋白大米饭、香椿炒蛋、清炒上海青",
    },
    highlights: ["体现华东偏清鲜口味", "虾仁、香椿等季节性食材更有地区辨识度"],
    totals: { energy: 1833, protein: 48, fat: 50, carbs: 303, sodium: 1955, potassium: 1896, phosphorus: 837 },
  },
  {
    id: "dp-hz-spring-12",
    region: "华中地区",
    season: "春季",
    stageGroup: "1-2",
    title: "华中地区春季整日方案",
    sourceNote: "指南附录 3，第 50 页，慢性肾脏病 1-2 期春季食谱。",
    meals: {
      breakfast: "青菜香菇包、牛奶",
      snack1: "藕粉蜂蜜糊",
      lunch: "大米饭、青椒萝卜丝、西红柿豆腐汤",
      snack2: "猕猴桃",
      dinner: "山药大米饭、清炒油菜、胡萝卜炒牛腩",
    },
    highlights: ["米饭为主，蔬菜选择更丰富", "更适合华中地区家庭做整日参考"],
    totals: { energy: 1803, protein: 49, fat: 52, carbs: 297, sodium: 2130, potassium: 2146, phosphorus: 852 },
  },
  {
    id: "dp-hz-spring-35",
    region: "华中地区",
    season: "春季",
    stageGroup: "3-5",
    title: "华中地区春季整日方案",
    sourceNote: "指南附录 3，第 51 页，慢性肾脏病 3-5 期春季食谱。",
    meals: {
      breakfast: "馒头、蒸鸡蛋、牛奶",
      snack1: "面包",
      lunch: "低蛋白大米饭、清炒牛肉、青笋拌粉丝",
      snack2: "猴头土豆",
      dinner: "低蛋白大米饭、蒜苔炒肉片、鱼香茄子",
    },
    highlights: ["低蛋白主食贯穿全天", "更适合 3-5 期患者长期参考"],
    totals: { energy: 1775, protein: 36, fat: 46, carbs: 311, sodium: 1702, potassium: 1511, phosphorus: 530 },
  },
  {
    id: "dp-xn-spring-12",
    region: "西南地区",
    season: "春季",
    stageGroup: "1-2",
    title: "西南地区春季整日方案",
    sourceNote: "指南附录 3，第 55 页，慢性肾脏病 1-2 期春季食谱。",
    meals: {
      breakfast: "肥肠粉、鸡蛋羹",
      snack1: "草莓",
      lunch: "米饭、玫瑰盐煎肉、蒜蓉生菜",
      snack2: "凉拌粉条",
      dinner: "酸辣粉、米饭、葱姜鲫鱼、炝拌豌豆苗",
    },
    highlights: ["保留西南地区粉面结构和少量辛香风味", "仍然通过份量控制压低盐和蛋白负担"],
    totals: { energy: 1744, protein: 47, fat: 53, carbs: 272, sodium: 1566, potassium: 1311, phosphorus: 667 },
  },
  {
    id: "dp-xn-spring-35",
    region: "西南地区",
    season: "春季",
    stageGroup: "3-5",
    title: "西南地区春季整日方案",
    sourceNote: "指南附录 3，第 56 页，慢性肾脏病 3-5 期春季食谱。",
    meals: {
      breakfast: "馒头、蒸鸡蛋、牛奶",
      snack1: "豆包",
      lunch: "低蛋白大米饭、青炒牛肉、青笋拌粉丝",
      snack2: "猴头土豆",
      dinner: "低蛋白大米饭、蒜苔炒肉片、鱼香茄子",
    },
    highlights: ["借用了西南家常炒菜结构，但主食已改成低蛋白版", "适合 3-5 期作地区化模板参考"],
    totals: { energy: 1775, protein: 36, fat: 46, carbs: 311, sodium: 1702, potassium: 1511, phosphorus: 530 },
  },
  {
    id: "dp-hn-spring-12",
    region: "华南地区",
    season: "春季",
    stageGroup: "1-2",
    title: "华南地区春季整日方案",
    sourceNote: "指南附录 3，第 60 页，慢性肾脏病 1-2 期春季食谱 1。",
    meals: {
      breakfast: "鸡蛋虾仁蒸粉丝",
      snack1: "雪梨",
      lunch: "低蛋白大米饭、豇豆花菇、蒜炒油麦菜",
      snack2: "葛粉甜羹",
      dinner: "米饭、南瓜蒸排骨、鲍大豆芽",
    },
    highlights: ["华南地区保留蒸菜和汤粉结构", "口味整体偏清淡，油盐控制更容易执行"],
    totals: { energy: 1853, protein: 48, fat: 63, carbs: 280, sodium: 1808, potassium: 1387, phosphorus: 608 },
  },
  {
    id: "dp-hn-spring-35",
    region: "华南地区",
    season: "春季",
    stageGroup: "3-5",
    title: "华南地区春季整日方案",
    sourceNote: "指南附录 3，第 62 页，慢性肾脏病 3-5 期春季食谱。",
    meals: {
      breakfast: "麦淀粉蒸软饼、娃娃菜",
      snack1: "苹果",
      lunch: "赤小豆米饭、香菇芋排骨、蒜炒油麦菜",
      snack2: "荔枝",
      dinner: "西红柿鸡蛋炒馓针",
    },
    highlights: ["低蛋白主食和小份豆类搭配更符合 3-5 期管理", "仍保留华南地区的清蒸和软烂口感"],
    totals: { energy: 1804, protein: 36, fat: 50, carbs: 302, sodium: 1842, potassium: 1813, phosphorus: 578 },
  },
  {
    id: "dp-ne-summer-12",
    region: "东北地区",
    season: "夏季",
    stageGroup: "1-2",
    title: "东北地区夏季整日方案",
    sourceNote: "指南附录 3，第 27 页，慢性肾脏病 1-2 期夏季食谱。",
    meals: {
      breakfast: "麦发糕、牛奶",
      snack1: "牛奶",
      lunch: "炒豆、二米饭、香菇胡萝卜鸡腿",
      snack2: "黄萝卜虾仁",
      dinner: "花卷、芦笋鸭肉、炒苋菜",
    },
    highlights: ["夏季以蔬菜和主食搭配为主，结构较轻", "适合作为东北夏季的一日模板"],
    totals: { energy: 1818, protein: 48, fat: 56, carbs: 286, sodium: 1557, potassium: 1649, phosphorus: 745 },
  },
  {
    id: "dp-ne-winter-12",
    region: "东北地区",
    season: "冬季",
    stageGroup: "1-2",
    title: "东北地区冬季整日方案",
    sourceNote: "指南附录 3，第 28 页，慢性肾脏病 1-2 期冬季食谱。",
    meals: {
      breakfast: "山药丝饼、牛奶、西芹拌腐竹",
      snack1: "甜瓜",
      lunch: "白菜猪肉粉条炖豆腐、油炒菠菜、杂粮饭",
      snack2: "核桃",
      dinner: "青椒炒蛋、小鸡炖蘑菇、馒头",
    },
    highlights: ["冬季加入山药、茯苓类食材思路", "全天热量和蛋白更平稳"],
    totals: { energy: 1811, protein: 47, fat: 66, carbs: 270, sodium: 1777, potassium: 2054, phosphorus: 808 },
  },
  {
    id: "dp-ne-summer-35",
    region: "东北地区",
    season: "夏季",
    stageGroup: "3-5",
    title: "东北地区夏季整日方案",
    sourceNote: "指南附录 3，第 29 页，慢性肾脏病 3-5 期夏季食谱。",
    meals: {
      breakfast: "西葫芦鸡蛋饼、菠菜海带根",
      snack1: "橘子",
      lunch: "黄黍土豆片、尖椒千页腐、低蛋白大米饭",
      snack2: "蓝莓",
      dinner: "红烧鲤鱼、老虎菜、二米饭",
    },
    highlights: ["低蛋白主食和小份优质蛋白并用", "更适合 3-5 期夏季执行"],
    totals: { energy: 1765, protein: 38, fat: 58, carbs: 278, sodium: 1566, potassium: 1996, phosphorus: 636 },
  },
  {
    id: "dp-ne-winter-35",
    region: "东北地区",
    season: "冬季",
    stageGroup: "3-5",
    title: "东北地区冬季整日方案",
    sourceNote: "指南附录 3，第 29 页，慢性肾脏病 3-5 期冬季食谱。",
    meals: {
      breakfast: "馒头、牛奶",
      snack1: "葡萄",
      lunch: "排骨炖豆角、凉拌猪皮、低蛋白大米饭",
      snack2: "沙果",
      dinner: "香煎豆腐、老黄瓜汤、杂粮饭",
    },
    highlights: ["保留东北炖菜结构，但主食已改为低蛋白版", "适合寒冷季节参考"],
    totals: { energy: 1745, protein: 32, fat: 63, carbs: 267, sodium: 2226, potassium: 1620, phosphorus: 574 },
  },
  {
    id: "dp-nw-summer-12",
    region: "西北地区",
    season: "夏季",
    stageGroup: "1-2",
    title: "西北地区夏季整日方案",
    sourceNote: "指南附录 3，第 32-33 页，慢性肾脏病 1-2 期夏季食谱。",
    meals: {
      breakfast: "土豆丝饼、酸奶、凉拌粉丝苦苣",
      snack1: "苹果",
      lunch: "低蛋白大米饭、葱烧黄虾丁、西红柿粉丝瓜、海米冬瓜汤",
      snack2: "鸭蛋",
      dinner: "蒸山药、馄饨、清炒芦蒿",
    },
    highlights: ["夏季瓜果和粉丝类搭配较多", "更贴近西北夏季饮食习惯"],
    totals: { energy: 1759, protein: 48, fat: 48, carbs: 294, sodium: 1938, potassium: 2991, phosphorus: 717 },
  },
  {
    id: "dp-nw-winter-12",
    region: "西北地区",
    season: "冬季",
    stageGroup: "1-2",
    title: "西北地区冬季整日方案",
    sourceNote: "指南附录 3，第 33 页，慢性肾脏病 1-2 期冬季食谱。",
    meals: {
      breakfast: "玉米面花卷、酸奶、鸡蛋卷、清炒西葫芦",
      snack1: "苹果",
      lunch: "蒸玉米、西红柿牛肉末、清炒蒜片",
      snack2: "鲜枣",
      dinner: "杂粮煎饼、莲子百合饭、鸡丝炒花菜",
    },
    highlights: ["冬季主食更偏温和软食", "乳制品和谷物搭配较充足"],
    totals: { energy: 1845, protein: 50, fat: 51, carbs: 301, sodium: 1845, potassium: 2628, phosphorus: 900 },
  },
  {
    id: "dp-hb-summer-12",
    region: "华北地区",
    season: "夏季",
    stageGroup: "1-2",
    title: "华北地区夏季整日方案",
    sourceNote: "指南附录 3，第 39 页，慢性肾脏病 1-2 期夏季食谱。",
    meals: {
      breakfast: "豆腐脑、馒头、拌芹菜",
      snack1: "桃子",
      lunch: "杂粮饭、木耳虾仁、炒山药木耳、素炒圆白菜",
      snack2: "梨",
      dinner: "烧麦、小米粥",
    },
    highlights: ["夏季蔬菜比例较高", "面食和小米搭配符合华北夏季家常结构"],
    totals: { energy: 1798, protein: 50, fat: 60, carbs: 272, sodium: 1744, potassium: 2256, phosphorus: 824 },
  },
  {
    id: "dp-hb-winter-12",
    region: "华北地区",
    season: "冬季",
    stageGroup: "1-2",
    title: "华北地区冬季整日方案",
    sourceNote: "指南附录 3，第 39 页，慢性肾脏病 1-2 期冬季食谱。",
    meals: {
      breakfast: "锅巴菜、煮鸡蛋、冲无糖藕粉",
      snack1: "橙子",
      lunch: "低蛋白大米饭、排骨炖白菜、炒鸡腿蘑",
      snack2: "梨",
      dinner: "炸酱面、菜心、黄豆汤",
    },
    highlights: ["冬季家常炖菜与面食比例更高", "油盐仍按指南做了压缩"],
    totals: { energy: 1792, protein: 48, fat: 56, carbs: 282, sodium: 1636, potassium: 2520, phosphorus: 771 },
  },
  {
    id: "dp-hb-summer-35",
    region: "华北地区",
    season: "夏季",
    stageGroup: "3-5",
    title: "华北地区夏季整日方案",
    sourceNote: "指南附录 3，第 40 页，慢性肾脏病 3-5 期夏季食谱。",
    meals: {
      breakfast: "低蛋白大米粥、猪肉大葱包子、洋生菜",
      snack1: "冲马蹄粉",
      lunch: "低蛋白大米饭、黄花鲫鱼、娃娃菜炒粉条",
      snack2: "樱桃",
      dinner: "茄子打卤面",
    },
    highlights: ["低蛋白大米饭和面食并行，适合夏季口味", "更贴近华北 3-5 期管理需求"],
    totals: { energy: 1793, protein: 34, fat: 45, carbs: 271, sodium: 3181, potassium: 1418, phosphorus: 571 },
  },
  {
    id: "dp-hb-autumn-35b",
    region: "华北地区",
    season: "秋季",
    stageGroup: "3-5",
    title: "华北地区秋季整日方案 2",
    sourceNote: "指南附录 3，第 40 页，慢性肾脏病 3-5 期秋季食谱。",
    meals: {
      breakfast: "低蛋白大米粥、面包、温拌西兰花",
      snack1: "橙子",
      lunch: "低蛋白大米饭、清蒸鲈鱼、干煸豆角、素炒圆白菜",
      snack2: "梨",
      dinner: "猪肉米包、芋青瓜丝、冲无糖藕粉",
    },
    highlights: ["秋季以软饭和蒸煮为主", "更适合需要稳妥控蛋白的人群"],
    totals: { energy: 1792, protein: 36, fat: 51, carbs: 306, sodium: 1800, potassium: 1917, phosphorus: 730 },
  },
  {
    id: "dp-hd-summer-12",
    region: "华东地区",
    season: "夏季",
    stageGroup: "1-2",
    title: "华东地区夏季整日方案",
    sourceNote: "指南附录 3，第 44 页，慢性肾脏病 1-2 期夏季食谱。",
    meals: {
      breakfast: "花卷、玉米燕麦浆、石榴",
      snack1: "石榴",
      lunch: "扁米饭、板栗烧鸡、西芹炒白果",
      snack2: "罗汉果雪梨汤",
      dinner: "低蛋白大米饭、油焖蚕豆、青椒土豆丝",
    },
    highlights: ["夏季汤饮和水果加餐更多", "体现华东清鲜但有变化的口味结构"],
    totals: { energy: 1828, protein: 48, fat: 55, carbs: 305, sodium: 2170, potassium: 1676, phosphorus: 899 },
  },
  {
    id: "dp-hd-autumn-12",
    region: "华东地区",
    season: "秋季",
    stageGroup: "1-2",
    title: "华东地区秋季整日方案",
    sourceNote: "指南附录 3，第 44 页，慢性肾脏病 1-2 期秋季食谱。",
    meals: {
      breakfast: "生煎、牛奶",
      snack1: "烤红薯",
      lunch: "高良姜炖牛肉、清炒时蔬",
      snack2: "无糖藕粉",
      dinner: "低蛋白大米饭、白菜粉丝煲",
    },
    highlights: ["秋季更偏温热食物", "适合华东家庭作整日模板参考"],
    totals: { energy: 1812, protein: 49, fat: 51, carbs: 294, sodium: 1860, potassium: 1699, phosphorus: 842 },
  },
  {
    id: "dp-hd-summer-35",
    region: "华东地区",
    season: "夏季",
    stageGroup: "3-5",
    title: "华东地区夏季整日方案",
    sourceNote: "指南附录 3，第 47 页，慢性肾脏病 3-5 期夏季食谱。",
    meals: {
      breakfast: "南瓜莲子鸡蛋羹、小米糕",
      snack1: "鲜覆盆子",
      lunch: "二米饭、苦瓜炒肉、凉拌藕片",
      snack2: "麦式绿豆汤",
      dinner: "豌豆焖饭、苋油麦生菜、丝瓜汤",
    },
    highlights: ["低蛋白主食与苦瓜、丝瓜等夏季蔬菜搭配", "更适合 3-5 期夏季管理"],
    totals: { energy: 1828, protein: 36, fat: 51, carbs: 313, sodium: 1753, potassium: 1998, phosphorus: 705 },
  },
  {
    id: "dp-hz-summer-35",
    region: "华中地区",
    season: "夏季",
    stageGroup: "3-5",
    title: "华中地区夏季整日方案",
    sourceNote: "指南附录 3，第 50 页，慢性肾脏病 3-5 期夏季食谱。",
    meals: {
      breakfast: "凉拌粉丝、西红柿炒蛋",
      snack1: "玉米羹",
      lunch: "大米饭、地三鲜、黄芪肉片",
      snack2: "苹果",
      dinner: "薏米大米饭、彩椒西兰花、丝瓜肉片",
    },
    highlights: ["夏季食材更偏茄果和瓜类", "适合作为华中地区 3-5 期夏季样板"],
    totals: { energy: 1819, protein: 36, fat: 48, carbs: 318, sodium: 1817, potassium: 1861, phosphorus: 627 },
  },
  {
    id: "dp-hn-autumn-12",
    region: "华南地区",
    season: "秋季",
    stageGroup: "1-2",
    title: "华南地区秋季整日方案",
    sourceNote: "指南附录 3，第 59 页，慢性肾脏病 1-2 期秋季食谱 1。",
    meals: {
      breakfast: "素拌腐皮、啵呀",
      snack1: "苹果",
      lunch: "低蛋白大米饭、橘皮焖鸡、素炒菜心",
      snack2: "麦淀粉蒸糕",
      dinner: "米饭、素苏香草鱼、蒜炒西葫芦",
    },
    highlights: ["保留华南清淡蒸煮习惯", "秋季更适合做长期执行样板"],
    totals: { energy: 1807, protein: 52, fat: 54, carbs: 288, sodium: 1910, potassium: 1563, phosphorus: 717 },
  },
  {
    id: "dp-hn-winter-12",
    region: "华南地区",
    season: "冬季",
    stageGroup: "1-2",
    title: "华南地区冬季整日方案",
    sourceNote: "指南附录 3，第 59 页，慢性肾脏病 1-2 期冬季食谱 2。",
    meals: {
      breakfast: "猪肉蒸红薯粉、苹果",
      snack1: "橄榄茶",
      lunch: "米饭、姜丝炒牛肉、素炒卷心菜",
      snack2: "橙桃",
      dinner: "米饭、清蒸鲈鱼、素炒芥瓜",
    },
    highlights: ["冬季以蒸和快炒为主", "适合华南偏清淡口味的冬季整日参考"],
    totals: { energy: 1821, protein: 48, fat: 46, carbs: 305, sodium: 1719, potassium: 1567, phosphorus: 659 },
  },
  {
    id: "dp-hn-winter-35",
    region: "华南地区",
    season: "冬季",
    stageGroup: "3-5",
    title: "华南地区冬季整日方案",
    sourceNote: "指南附录 3，第 60 页，慢性肾脏病 3-5 期冬季食谱。",
    meals: {
      breakfast: "麦淀粉蒸软饼、娃娃菜",
      snack1: "苹果",
      lunch: "春笋芋排骨、蒜炒油麦菜",
      snack2: "荔枝",
      dinner: "西红柿鸡蛋炒馓针",
    },
    highlights: ["以低蛋白面饼和小份排骨配菜为主", "适合冬季 3-5 期稳妥执行"],
    totals: { energy: 1804, protein: 36, fat: 50, carbs: 302, sodium: 1842, potassium: 1813, phosphorus: 578 },
  },
  {
    id: "dp-hn-summer-35",
    region: "华南地区",
    season: "夏季",
    stageGroup: "3-5",
    title: "华南地区夏季整日方案",
    sourceNote: "指南附录 3，第 60 页，慢性肾脏病 3-5 期夏季食谱 1。",
    meals: {
      breakfast: "水晶肠、小麦淀粉软饼、低脂牛奶、蒜拌莴笋丝",
      snack1: "金桔",
      lunch: "低筋面条、洋葱白果炒牛肉、姜丝炒生菜",
      snack2: "苹果",
      dinner: "麦淀粉饺子",
    },
    highlights: ["夏季主食更偏软面和清炒蔬菜", "华南 3-5 期的低蛋白结构更明显"],
    totals: { energy: 1717, protein: 37, fat: 60, carbs: 260, sodium: 1958, potassium: 1588, phosphorus: 643 },
  },
];
